// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/leak_tracker/src/leak_tracking/primitives/_gc_counter.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk'], (function load__packages__leak_tracker__src__leak_tracking__primitives___gc_counter_dart(dart_sdk) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const developer = dart_sdk.developer;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  var _gc_counter = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    int: () => (T.int = dart.constFn(dart_rti.findType("core|int")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  var I = ["package:leak_tracker/src/leak_tracking/primitives/_gc_counter.dart"];
  _gc_counter.GcCounter = class GcCounter extends core.Object {
    get gcCount() {
      return developer.reachabilityBarrier;
    }
    static ['_#new#tearOff']() {
      return new _gc_counter.GcCounter.new();
    }
  };
  (_gc_counter.GcCounter.new = function() {
    ;
  }).prototype = _gc_counter.GcCounter.prototype;
  dart.addTypeTests(_gc_counter.GcCounter);
  dart.addRtiResources(_gc_counter.GcCounter, ["leak_tracker__src__leak_tracking__primitives___gc_counter|GcCounter"]);
  dart.addTypeCaches(_gc_counter.GcCounter);
  dart.setGetterSignature(_gc_counter.GcCounter, () => dart.global.Object.setPrototypeOf({gcCount: T.int()}, dart.getGetters(dart.global.Object.getPrototypeOf(_gc_counter.GcCounter))));
  dart.setLibraryUri(_gc_counter.GcCounter, I[0]);
  _gc_counter.shouldObjectBeGced = function shouldObjectBeGced(opts) {
    let gcCountAtDisposal = opts && 'gcCountAtDisposal' in opts ? opts.gcCountAtDisposal : null;
    let timeAtDisposal = opts && 'timeAtDisposal' in opts ? opts.timeAtDisposal : null;
    let currentGcCount = opts && 'currentGcCount' in opts ? opts.currentGcCount : null;
    let currentTime = opts && 'currentTime' in opts ? opts.currentTime : null;
    let disposalTime = opts && 'disposalTime' in opts ? opts.disposalTime : null;
    let numberOfGcCycles = opts && 'numberOfGcCycles' in opts ? opts.numberOfGcCycles : null;
    return currentGcCount - gcCountAtDisposal >= numberOfGcCycles && currentTime.difference(timeAtDisposal)['>='](disposalTime);
  };
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|int":{"core|num":[],"Comparable.T":"core|num","core|Comparable":["core|num"]},"core|num":{"Comparable.T":"core|num","core|Comparable":["core|num"]},"core|Comparable":{"Comparable.T":"1"}}'));
  dart.trackLibraries("packages/leak_tracker/src/leak_tracking/primitives/_gc_counter.dart", {
    "package:leak_tracker/src/leak_tracking/primitives/_gc_counter.dart": _gc_counter
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["_gc_counter.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;AASqB;IAAmB;;;;;;;EACxC;;;;;;;QAMe;QACK;QACL;QACK;QACA;QACL;AAEX,UAAA,AAAe,AAAoB,AAAoB,eAAzC,GAAG,iBAAiB,IAAI,gBAAgB,IACtD,AAAY,AAA2B,WAA5B,YAAY,cAAc,QAAK,YAAY","file":"../../../../../../../../../../packages/leak_tracker/src/leak_tracking/primitives/_gc_counter.dart.lib.js"}');
  // Exports:
  return {
    src__leak_tracking__primitives___gc_counter: _gc_counter
  };
}));

//# sourceMappingURL=_gc_counter.dart.lib.js.map
