// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/leak_tracker/src/shared/_primitives.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk'], (function load__packages__leak_tracker__src__shared___primitives_dart(dart_sdk) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  var _primitives = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    VoidToString: () => (T.VoidToString = dart.constFn(dart_rti.findType("core|String()")))(),
    String: () => (T.String = dart.constFn(dart_rti.findType("core|String")))(),
    ListOfLinks: () => (T.ListOfLinks = dart.constFn(dart_rti.findType("core|List<leak_tracker__src__shared___primitives|Links>")))(),
    StringN: () => (T.StringN = dart.constFn(dart_rti.findType("core|String?")))(),
    Links: () => (T.Links = dart.constFn(dart_rti.findType("leak_tracker__src__shared___primitives|Links")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [_Enum__name]: "gitHubTroubleshooting",
        [_Enum_index]: 0,
        hash: null,
        url: "https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md"
      }, _primitives.Links.prototype));
    },
    get C0() {
      return C[0] = dart.constList([C[1] || CT.C1], T.Links());
    }
  }, false);
  var C = Array(2).fill(void 0);
  var I = [
    "package:leak_tracker/src/shared/_primitives.dart",
    "dart:core"
  ];
  var value$ = dart.privateName(_primitives, "ObjectRef.value");
  var _eval = dart.privateName(dart_rti, "_eval");
  var _as = dart.privateName(dart_rti, "_as");
  const _is_ObjectRef_default = Symbol('_is_ObjectRef_default');
  _primitives.ObjectRef$ = dart.generic(T => {
    var __t$ObjectRefOfT = () => (__t$ObjectRefOfT = dart.constFn(T[_eval]("leak_tracker__src__shared___primitives|ObjectRef<0>")))();
    class ObjectRef extends core.Object {
      get value() {
        return this[value$];
      }
      set value(value) {
        this[value$] = T[_as](value);
      }
      static ['_#new#tearOff'](T, value) {
        return new (_primitives.ObjectRef$(T)).new(value);
      }
    }
    (ObjectRef.new = function(value) {
      this[value$] = value;
      this.$ti = this.$ti || __t$ObjectRefOfT();
      ;
    }).prototype = ObjectRef.prototype;
    dart.addTypeTests(ObjectRef);
    ObjectRef.prototype[_is_ObjectRef_default] = true;
    dart.addRtiResources(ObjectRef, ["leak_tracker__src__shared___primitives|ObjectRef"]);
    dart.addTypeCaches(ObjectRef);
    dart.setLibraryUri(ObjectRef, I[0]);
    dart.setFieldSignature(ObjectRef, () => dart.global.Object.setPrototypeOf({value: {type: T, isConst: false, isFinal: false}}, dart.getFields(dart.global.Object.getPrototypeOf(ObjectRef))));
    return ObjectRef;
  });
  _primitives.ObjectRef = _primitives.ObjectRef$();
  dart.addTypeTests(_primitives.ObjectRef, _is_ObjectRef_default);
  var _name = dart.privateName(core, "_name");
  var _enumToString = dart.privateName(core, "_enumToString");
  var _Enum__name = dart.privateName(core, "_Enum._name");
  var _Enum_index = dart.privateName(core, "_Enum.index");
  _primitives.Links = class Links extends core._Enum {
    [_enumToString]() {
      return "Links." + this[_name];
    }
    static ['_#new#tearOff'](t$36$35index, t$36$35name, url, hash) {
      return new _primitives.Links.new(t$36$35index, t$36$35name, url, hash);
    }
    get value() {
      if (this.hash == null) return this.url;
      return this.url + "#" + dart.str(this.hash);
    }
  };
  (_primitives.Links.new = function(t$36$35index, t$36$35name, url, hash) {
    this.url = url;
    this.hash = hash;
    dart.global.Object.getPrototypeOf(_primitives.Links).new.call(this, t$36$35index, t$36$35name);
    ;
  }).prototype = _primitives.Links.prototype;
  dart.addTypeTests(_primitives.Links);
  dart.addRtiResources(_primitives.Links, ["leak_tracker__src__shared___primitives|Links"]);
  dart.addTypeCaches(_primitives.Links);
  dart.setMethodSignature(_primitives.Links, () => dart.global.Object.setPrototypeOf({[_enumToString]: T.VoidToString()}, dart.getMethods(dart.global.Object.getPrototypeOf(_primitives.Links))));
  dart.setGetterSignature(_primitives.Links, () => dart.global.Object.setPrototypeOf({value: T.String()}, dart.getGetters(dart.global.Object.getPrototypeOf(_primitives.Links))));
  dart.setLibraryUri(_primitives.Links, I[0]);
  dart.setFieldSignature(_primitives.Links, () => dart.global.Object.setPrototypeOf({
    url: {type: T.String(), isConst: false, isFinal: true, libraryUri: I[1]},
    hash: {type: T.StringN(), isConst: false, isFinal: true, libraryUri: I[1]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(_primitives.Links))));
  dart.setStaticFieldSignature(_primitives.Links, () => ['values', 'gitHubTroubleshooting']);
  dart.defineLazy(_primitives.Links, {
    /*_primitives.Links.values*/get values() {
      return C[0] || CT.C0;
    },
    /*_primitives.Links.gitHubTroubleshooting*/get gitHubTroubleshooting() {
      return C[1] || CT.C1;
    }
  }, false);
  _primitives.standardIdentityHashCoder = function standardIdentityHashCoder(object) {
    return core.identityHashCode(object);
  };
  _primitives.fullClassName = function fullClassName(opts) {
    let library = opts && 'library' in opts ? opts.library : null;
    let shortClassName = opts && 'shortClassName' in opts ? opts.shortClassName : null;
    return library + "/" + shortClassName;
  };
  dart.defineLazy(_primitives, {
    /*_primitives.leakTrackerStackTraceFragment*/get leakTrackerStackTraceFragment() {
      return "(package:leak_tracker/";
    },
    /*_primitives.leakTrackerYamlHeader*/get leakTrackerYamlHeader() {
      return "# The text is generated by leak_tracker.\n# For leak troubleshooting tips open:\n# " + _primitives.Links.gitHubTroubleshooting.value + "\n";
    }
  }, false);
  dart.moduleConstCaches.set("packages/leak_tracker/src/shared/_primitives.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"leak_tracker__src__shared___primitives|ObjectRef":{"ObjectRef.T":"1"},"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"core|List":{"List.E":"1","Iterable.E":"1","core|Iterable":["1"],"_ListIterable.E":"1","core|_ListIterable":["1"],"EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"]},"core|Iterable":{"Iterable.E":"1"},"core|_ListIterable":{"_ListIterable.E":"1","EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"],"Iterable.E":"1","core|Iterable":["1"]},"_internal|EfficientLengthIterable":{"EfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"_internal|HideEfficientLengthIterable":{"HideEfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"leak_tracker__src__shared___primitives|Links":{"core|_Enum":[],"core|Enum":[]},"core|_Enum":{"core|Enum":[]}}'));
  dart.trackLibraries("packages/leak_tracker/src/shared/_primitives.dart", {
    "package:leak_tracker/src/shared/_primitives.dart": _primitives
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["_primitives.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;MAuBI;;;;;;;;;;;MADa;;;IAAM;;;;;;;;;;;;;;;;;;IA4BvB;;;;;AAHI,UAAI,AAAK,mBAAS,MAAO;AACzB,YAAS,AAAU,YAAP,eAAE;IAChB;;+DAPiB,KAAU;IAAV;IAAU;AAArB;;EAA0B;;;;;;;;;;;;;MAP7B,wBAAM;;;MACT,uCAAqB;;;;6EA1Bc;AAAW,iCAAiB,MAAM;EAAC;;QAMtD;QACA;AAEd,UAAE,AAAwB,QAAjB,SAAE,cAAc;EAAC;;MANxB,yCAA6B;;;MAa7B,iCAAqB;YAAG,AAI3B,yFADO,AAAsB,gDAAM","file":"../../../../../../../../../packages/leak_tracker/src/shared/_primitives.dart.lib.js"}');
  // Exports:
  return {
    src__shared___primitives: _primitives
  };
}));

//# sourceMappingURL=_primitives.dart.lib.js.map
