// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/leak_tracker/src/devtools_integration/_registration.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/leak_tracker/src/devtools_integration/delivery.dart', 'packages/leak_tracker/src/devtools_integration/messages.dart', 'packages/leak_tracker/src/shared/_util.dart'], (function load__packages__leak_tracker__src__devtools_integration___registration_dart(dart_sdk, packages__leak_tracker__src__devtools_integration__delivery$46dart, packages__leak_tracker__src__devtools_integration__messages$46dart, packages__leak_tracker__src__shared___util$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const developer = dart_sdk.developer;
  const convert = dart_sdk.convert;
  const _js_helper = dart_sdk._js_helper;
  const async = dart_sdk.async;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const delivery = packages__leak_tracker__src__devtools_integration__delivery$46dart.src__devtools_integration__delivery;
  const messages = packages__leak_tracker__src__devtools_integration__messages$46dart.src__devtools_integration__messages;
  const _util = packages__leak_tracker__src__shared___util$46dart.src__shared___util;
  var _registration = Object.create(dart.library);
  var $runtimeType = dartx.runtimeType;
  var $toString = dartx.toString;
  var $contains = dartx.contains;
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    ServiceExtensionResponse: () => (T.ServiceExtensionResponse = dart.constFn(dart_rti.findType("developer|ServiceExtensionResponse")))(),
    StringAndMapOfString$StringToFutureOfServiceExtensionResponse: () => (T.StringAndMapOfString$StringToFutureOfServiceExtensionResponse = dart.constFn(dart_rti.findType("async|Future<developer|ServiceExtensionResponse>(core|String,core|Map<core|String,core|String>)")))(),
    LeakTrackingTurnedOffError: () => (T.LeakTrackingTurnedOffError = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__messages|LeakTrackingTurnedOffError")))(),
    Object: () => (T.Object = dart.constFn(dart_rti.findType("core|Object")))(),
    RequestForLeakDetails: () => (T.RequestForLeakDetails = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__messages|RequestForLeakDetails")))(),
    FutureOfLeaks: () => (T.FutureOfLeaks = dart.constFn(dart_rti.findType("async|Future<leak_tracker__src__shared__shared_model|Leaks>")))(),
    UnexpectedRequestTypeError: () => (T.UnexpectedRequestTypeError = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__messages|UnexpectedRequestTypeError")))(),
    UnexpectedError: () => (T.UnexpectedError = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__messages|UnexpectedError")))(),
    LeakTrackingStarted: () => (T.LeakTrackingStarted = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__messages|LeakTrackingStarted")))(),
    ArgumentError: () => (T.ArgumentError = dart.constFn(dart_rti.findType("core|ArgumentError")))()
  };
  var G = {
    ResponseFromAppOfLeakTrackingTurnedOffError: () => (G.ResponseFromAppOfLeakTrackingTurnedOffError = dart.constFn(delivery.ResponseFromApp$(T.LeakTrackingTurnedOffError())))(),
    RequestToAppOfObject: () => (G.RequestToAppOfObject = dart.constFn(delivery.RequestToApp$(T.Object())))(),
    ResponseFromAppOfFutureOfLeaks: () => (G.ResponseFromAppOfFutureOfLeaks = dart.constFn(delivery.ResponseFromApp$(T.FutureOfLeaks())))(),
    ResponseFromAppOfUnexpectedRequestTypeError: () => (G.ResponseFromAppOfUnexpectedRequestTypeError = dart.constFn(delivery.ResponseFromApp$(T.UnexpectedRequestTypeError())))(),
    ResponseFromAppOfUnexpectedError: () => (G.ResponseFromAppOfUnexpectedError = dart.constFn(delivery.ResponseFromApp$(T.UnexpectedError())))(),
    EventFromAppOfLeakTrackingStarted: () => (G.EventFromAppOfLeakTrackingStarted = dart.constFn(delivery.EventFromApp$(T.LeakTrackingStarted())))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  var I = ["file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/leak_tracker-10.0.0/lib/src/devtools_integration/_registration.dart"];
  var _is = dart.privateName(dart_rti, "_is");
  _registration.registerLeakTrackingServiceExtension = function registerLeakTrackingServiceExtension() {
    return _registration._registerServiceExtension(dart.fn((p0, p1) => async.async(T.ServiceExtensionResponse(), function*() {
      return new developer.ServiceExtensionResponse.result(convert.jsonEncode(new _js_helper.LinkedMap.new()));
    }), T.StringAndMapOfString$StringToFutureOfServiceExtensionResponse()));
  };
  _registration.initializeDevToolsIntegration = function initializeDevToolsIntegration(leakProvider) {
    function handler(method, parameters) {
      return async.async(T.ServiceExtensionResponse(), function* handler() {
        let t$360;
        try {
          if (!(method === "ext.dart.memoryLeakTracking")) dart.assertFailed(null, I[0], 38, 14, "method == memoryLeakTrackingExtensionName");
          let theLeakProvider = (t$360 = leakProvider.value, t$360 == null ? null : t$360.target);
          if (theLeakProvider == null) {
            return new (G.ResponseFromAppOfLeakTrackingTurnedOffError()).new(new messages.LeakTrackingTurnedOffError.new()).toServiceResponse();
          }
          let request = new (G.RequestToAppOfObject()).fromRequestParameters(parameters).message;
          if (T.RequestForLeakDetails()[_is](request)) {
            return new (G.ResponseFromAppOfFutureOfLeaks()).new(theLeakProvider.collectLeaks()).toServiceResponse();
          }
          return new (G.ResponseFromAppOfUnexpectedRequestTypeError()).new(new messages.UnexpectedRequestTypeError.new(dart.runtimeType(request))).toServiceResponse();
        } catch (t$36$35e) {
          let error = dart.getThrown(t$36$35e);
          let stack = dart.stackTrace(t$36$35e);
          if (T.Object()[_is](error)) {
            _util.printToConsole("Error handling leak tracking request from DevTools to application.");
            _util.printToConsole(error);
            _util.printToConsole(stack);
            return new (G.ResponseFromAppOfUnexpectedError()).new(new messages.UnexpectedError.new(error, stack)).toServiceResponse();
          } else
            throw t$36$35e;
        }
      });
    }
    dart.fn(handler, T.StringAndMapOfString$StringToFutureOfServiceExtensionResponse());
    let result = _registration._registerServiceExtension(handler);
    new (G.EventFromAppOfLeakTrackingStarted()).new(new messages.LeakTrackingStarted.new("1")).post();
    return result;
  };
  _registration._registerServiceExtension = function _registerServiceExtension(handler) {
    if (_registration._extentsionRegistered) return false;
    try {
      developer.registerExtension("ext.dart.memoryLeakTracking", handler);
      _registration._extentsionRegistered = true;
      return true;
    } catch (t$36$35e) {
      let ex = dart.getThrown(t$36$35e);
      if (T.ArgumentError()[_is](ex)) {
        let isAlreadyRegisteredError = dart.toString(ex)[$contains]("registered");
        if (isAlreadyRegisteredError) {
          return false;
        } else {
          dart.rethrow(t$36$35e);
        }
      } else
        throw t$36$35e;
    }
  };
  dart.defineLazy(_registration, {
    /*_registration._extentsionRegistered*/get _extentsionRegistered() {
      return false;
    },
    set _extentsionRegistered(value) {}
  }, false);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"async|Future":{"Future.T":"1"},"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"core|Map":{"Map.K":"1","Map.V":"2"},"core|ArgumentError":{"core|Error":[]}}'));
  dart.trackLibraries("packages/leak_tracker/src/devtools_integration/_registration.dart", {
    "package:leak_tracker/src/devtools_integration/_registration.dart": _registration
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["_registration.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;AAsB+C,mDACzC,SAAC,IAAI;AAAa,YAAyB,+CAAO,mBAAW;IAAI;EAClE;uFAMqC;AAExC,aAAiC,QACxB,QACa;AAFkB;;AAItC;AACE,gBAAO,AAAO,MAAD;AAEP,yCAAkB,AAAa,YAAD,wBAAC,OAAO;AAE5C,cAAI,AAAgB,eAAD;AACjB,kBAAO,AACF,2DADkB;;AAInB,wBAAuB,AAAkC,qDAAZ,UAAU;AAE7D,cAAY,+BAAR,OAAO;AACT,kBAAO,AACF,8CADkB,AAAgB,eAAD;;AAIxC,gBAAO,AAEL,2DADA,4CAAmC,iBAAR,OAAO;;cAE7B;cAAO;AAAd;AACA,iCACE;AAEF,iCAAe,KAAK;AACpB,iCAAe,KAAK;AAEpB,kBAAO,AAA+C,gDAA/B,iCAAgB,KAAK,EAAE,KAAK;;;;MAEvD;;;AAEM,iBAAS,wCAA0B,OAAO;AAEiB,IAAjE,gDAAa;AAEb,UAAO,OAAM;EACf;+EAIM;AAEJ,QAAI,qCAAuB,MAAO;AAClC;AACE,iEAEE,OAAO;AAET,4CAAwB;AAExB,YAAO;;UAEiB;AAAxB;AAEM,uCAA8B,AAAW,cAAd,EAAE,aAAqB;AACxD,YAAI,wBAAwB;AAC1B,gBAAO;;AAEP;;;;;EAGN;;MAnFK,mCAAqB;YAAG","file":"../../../../../../../../../packages/leak_tracker/src/devtools_integration/_registration.dart.lib.js"}');
  // Exports:
  return {
    src__devtools_integration___registration: _registration
  };
}));

//# sourceMappingURL=_registration.dart.lib.js.map
