// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/flexi_chip/src/container.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/flutter/src/widgets/unique_widget.dart'], (function load__packages__flexi_chip__src__container_dart(dart_sdk, packages__flutter__src__widgets__unique_widget$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const ui = dart_sdk.ui;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const widget_inspector = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__widget_inspector;
  const basic = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__basic;
  const proxy_box = packages__flutter__src__widgets__unique_widget$46dart.src__rendering__proxy_box;
  const framework = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__framework;
  const custom_paint = packages__flutter__src__widgets__unique_widget$46dart.src__rendering__custom_paint;
  var container = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    BuildContextToWidget: () => (T.BuildContextToWidget = dart.constFn(dart_rti.findType("flutter__src__widgets__framework|Widget(flutter__src__widgets__framework|BuildContext)")))(),
    Widget: () => (T.Widget = dart.constFn(dart_rti.findType("flutter__src__widgets__framework|Widget")))(),
    double: () => (T.double = dart.constFn(dart_rti.findType("core|double")))(),
    ColorN: () => (T.ColorN = dart.constFn(dart_rti.findType("ui|Color?")))(),
    Color: () => (T.Color = dart.constFn(dart_rti.findType("ui|Color")))(),
    ShapeBorderN: () => (T.ShapeBorderN = dart.constFn(dart_rti.findType("flutter__src__painting__borders|ShapeBorder?")))(),
    Clip: () => (T.Clip = dart.constFn(dart_rti.findType("ui|Clip")))(),
    ShapeBorder: () => (T.ShapeBorder = dart.constFn(dart_rti.findType("flutter__src__painting__borders|ShapeBorder")))(),
    TextDirectionN: () => (T.TextDirectionN = dart.constFn(dart_rti.findType("ui|TextDirection?")))(),
    bool: () => (T.bool = dart.constFn(dart_rti.findType("core|bool")))(),
    ShapeBorderPainter: () => (T.ShapeBorderPainter = dart.constFn(dart_rti.findType("flexi_chip__src__container|ShapeBorderPainter")))(),
    CanvasAndSizeTovoid: () => (T.CanvasAndSizeTovoid = dart.constFn(dart_rti.findType("~(ui|Canvas,ui|Size)")))(),
    ObjectNTobool: () => (T.ObjectNTobool = dart.constFn(dart_rti.findType("core|bool(core|Object?)")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [Color_value]: 4278190080.0
      }, ui.Color.prototype));
    },
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [_Enum__name]: "antiAlias",
        [_Enum_index]: 2
      }, ui.Clip.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ChipContainer",
        [_Location_column]: 9,
        [_Location_line]: 4,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C3() {
      return C[3] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "SizedBox",
        [_Location_column]: 23,
        [_Location_line]: 33,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C4() {
      return C[4] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ShapeBorderPaint",
        [_Location_column]: 18,
        [_Location_line]: 39,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C5() {
      return C[5] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ClipPath",
        [_Location_column]: 14,
        [_Location_line]: 47,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C6() {
      return C[6] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "PhysicalModel",
        [_Location_column]: 14,
        [_Location_line]: 55,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C7() {
      return C[7] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "PhysicalShape",
        [_Location_column]: 12,
        [_Location_line]: 64,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C8() {
      return C[8] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ShapeBorderPaint",
        [_Location_column]: 9,
        [_Location_line]: 76,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    },
    get C9() {
      return C[9] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "CustomPaint",
        [_Location_column]: 12,
        [_Location_line]: 92,
        [_Location_file]: "file:///Users/haggaibarel/.pub-cache/hosted/pub.dev/flexi_chip-1.0.8/lib/src/container.dart"
      }, widget_inspector._Location.prototype));
    }
  }, false);
  var C = Array(10).fill(void 0);
  var I = [
    "package:flexi_chip/src/container.dart",
    "package:flutter/src/widgets/framework.dart",
    "dart:core",
    "dart:ui",
    "package:flutter/src/painting/borders.dart"
  ];
  var child$ = dart.privateName(container, "ChipContainer.child");
  var height$ = dart.privateName(container, "ChipContainer.height");
  var color$ = dart.privateName(container, "ChipContainer.color");
  var shadowColor$ = dart.privateName(container, "ChipContainer.shadowColor");
  var elevation$ = dart.privateName(container, "ChipContainer.elevation");
  var shape$ = dart.privateName(container, "ChipContainer.shape");
  var clipBehavior$ = dart.privateName(container, "ChipContainer.clipBehavior");
  var Color_value = dart.privateName(ui, "Color.value");
  var _Enum__name = dart.privateName(core, "_Enum._name");
  var _Enum_index = dart.privateName(core, "_Enum.index");
  var _Location_name = dart.privateName(widget_inspector, "_Location.name");
  var _Location_column = dart.privateName(widget_inspector, "_Location.column");
  var _Location_line = dart.privateName(widget_inspector, "_Location.line");
  var _Location_file = dart.privateName(widget_inspector, "_Location.file");
  container.ChipContainer = class ChipContainer extends framework.StatelessWidget {
    get child() {
      return this[child$];
    }
    set child(value) {
      super.child = value;
    }
    get height() {
      return this[height$];
    }
    set height(value) {
      super.height = value;
    }
    get color() {
      return this[color$];
    }
    set color(value) {
      super.color = value;
    }
    get shadowColor() {
      return this[shadowColor$];
    }
    set shadowColor(value) {
      super.shadowColor = value;
    }
    get elevation() {
      return this[elevation$];
    }
    set elevation(value) {
      super.elevation = value;
    }
    get shape() {
      return this[shape$];
    }
    set shape(value) {
      super.shape = value;
    }
    get clipBehavior() {
      return this[clipBehavior$];
    }
    set clipBehavior(value) {
      super.clipBehavior = value;
    }
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      let child = opts && 'child' in opts ? opts.child : null;
      let height = opts && 'height' in opts ? opts.height : null;
      let color = opts && 'color' in opts ? opts.color : null;
      let shape = opts && 'shape' in opts ? opts.shape : null;
      let shadowColor = opts && 'shadowColor' in opts ? opts.shadowColor : C[0] || CT.C0;
      let clipBehavior = opts && 'clipBehavior' in opts ? opts.clipBehavior : C[1] || CT.C1;
      let elevation = opts && 'elevation' in opts ? opts.elevation : 0;
      return new container.ChipContainer.new({key: key, child: child, height: height, color: color, shape: shape, shadowColor: shadowColor, clipBehavior: clipBehavior, elevation: elevation, $creationLocationd_0dea112b090073317d4: C[2] || CT.C2});
    }
    build(context) {
      let textDirection = basic.Directionality.maybeOf(context);
      let borderClipper = this.shape == null ? null : new proxy_box.ShapeBorderClipper.new({textDirection: textDirection, shape: dart.nullCheck(this.shape)});
      let contents = new basic.SizedBox.new({height: this.height, child: this.child, $creationLocationd_0dea112b090073317d4: C[3] || CT.C3});
      if (this.shape != null) {
        contents = new container.ShapeBorderPaint.new({shape: dart.nullCheck(this.shape), textDirection: textDirection, child: contents, $creationLocationd_0dea112b090073317d4: C[4] || CT.C4});
      }
      if (this.color == null) {
        return new basic.ClipPath.new({clipper: borderClipper, clipBehavior: this.clipBehavior, child: contents, $creationLocationd_0dea112b090073317d4: C[5] || CT.C5});
      }
      if (this.shape == null) {
        return new basic.PhysicalModel.new({color: dart.nullCheck(this.color), elevation: this.elevation, shadowColor: this.shadowColor, clipBehavior: this.clipBehavior, child: contents, $creationLocationd_0dea112b090073317d4: C[6] || CT.C6});
      }
      return new basic.PhysicalShape.new({color: dart.nullCheck(this.color), elevation: this.elevation, shadowColor: this.shadowColor, clipBehavior: this.clipBehavior, clipper: dart.nullCheck(borderClipper), child: contents, $creationLocationd_0dea112b090073317d4: C[7] || CT.C7});
    }
  };
  (container.ChipContainer.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let child = opts && 'child' in opts ? opts.child : null;
    let height = opts && 'height' in opts ? opts.height : null;
    let color = opts && 'color' in opts ? opts.color : null;
    let shape = opts && 'shape' in opts ? opts.shape : null;
    let shadowColor = opts && 'shadowColor' in opts ? opts.shadowColor : C[0] || CT.C0;
    let clipBehavior = opts && 'clipBehavior' in opts ? opts.clipBehavior : C[1] || CT.C1;
    let elevation = opts && 'elevation' in opts ? opts.elevation : 0;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    this[child$] = child;
    this[height$] = height;
    this[color$] = color;
    this[shape$] = shape;
    this[shadowColor$] = shadowColor;
    this[clipBehavior$] = clipBehavior;
    this[elevation$] = elevation;
    dart.global.Object.getPrototypeOf(container.ChipContainer).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = container.ChipContainer.prototype;
  dart.addTypeTests(container.ChipContainer);
  dart.addRtiResources(container.ChipContainer, ["flexi_chip__src__container|ChipContainer"]);
  dart.addTypeCaches(container.ChipContainer);
  dart.setMethodSignature(container.ChipContainer, () => dart.global.Object.setPrototypeOf({build: T.BuildContextToWidget()}, dart.getMethods(dart.global.Object.getPrototypeOf(container.ChipContainer))));
  dart.setLibraryUri(container.ChipContainer, I[0]);
  dart.setFieldSignature(container.ChipContainer, () => dart.global.Object.setPrototypeOf({
    child: {type: T.Widget(), isConst: false, isFinal: true, libraryUri: I[1]},
    height: {type: T.double(), isConst: false, isFinal: true, libraryUri: I[2]},
    color: {type: T.ColorN(), isConst: false, isFinal: true, libraryUri: I[3]},
    shadowColor: {type: T.Color(), isConst: false, isFinal: true, libraryUri: I[3]},
    elevation: {type: T.double(), isConst: false, isFinal: true, libraryUri: I[2]},
    shape: {type: T.ShapeBorderN(), isConst: false, isFinal: true, libraryUri: I[4]},
    clipBehavior: {type: T.Clip(), isConst: false, isFinal: true, libraryUri: I[3]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(container.ChipContainer))));
  var child$0 = dart.privateName(container, "ShapeBorderPaint.child");
  var shape$0 = dart.privateName(container, "ShapeBorderPaint.shape");
  var textDirection$ = dart.privateName(container, "ShapeBorderPaint.textDirection");
  var isForeground$ = dart.privateName(container, "ShapeBorderPaint.isForeground");
  container.ShapeBorderPaint = class ShapeBorderPaint extends framework.StatelessWidget {
    get child() {
      return this[child$0];
    }
    set child(value) {
      super.child = value;
    }
    get shape() {
      return this[shape$0];
    }
    set shape(value) {
      super.shape = value;
    }
    get textDirection() {
      return this[textDirection$];
    }
    set textDirection(value) {
      super.textDirection = value;
    }
    get isForeground() {
      return this[isForeground$];
    }
    set isForeground(value) {
      super.isForeground = value;
    }
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      let child = opts && 'child' in opts ? opts.child : null;
      let shape = opts && 'shape' in opts ? opts.shape : null;
      let textDirection = opts && 'textDirection' in opts ? opts.textDirection : null;
      let isForeground = opts && 'isForeground' in opts ? opts.isForeground : true;
      return new container.ShapeBorderPaint.new({key: key, child: child, shape: shape, textDirection: textDirection, isForeground: isForeground, $creationLocationd_0dea112b090073317d4: C[8] || CT.C8});
    }
    build(context) {
      let painter = new container.ShapeBorderPainter.new(this.shape, this.textDirection);
      return new basic.CustomPaint.new({painter: this.isForeground ? null : painter, foregroundPainter: this.isForeground ? painter : null, child: this.child, $creationLocationd_0dea112b090073317d4: C[9] || CT.C9});
    }
  };
  (container.ShapeBorderPaint.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let child = opts && 'child' in opts ? opts.child : null;
    let shape = opts && 'shape' in opts ? opts.shape : null;
    let textDirection = opts && 'textDirection' in opts ? opts.textDirection : null;
    let isForeground = opts && 'isForeground' in opts ? opts.isForeground : true;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    this[child$0] = child;
    this[shape$0] = shape;
    this[textDirection$] = textDirection;
    this[isForeground$] = isForeground;
    dart.global.Object.getPrototypeOf(container.ShapeBorderPaint).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = container.ShapeBorderPaint.prototype;
  dart.addTypeTests(container.ShapeBorderPaint);
  dart.addRtiResources(container.ShapeBorderPaint, ["flexi_chip__src__container|ShapeBorderPaint"]);
  dart.addTypeCaches(container.ShapeBorderPaint);
  dart.setMethodSignature(container.ShapeBorderPaint, () => dart.global.Object.setPrototypeOf({build: T.BuildContextToWidget()}, dart.getMethods(dart.global.Object.getPrototypeOf(container.ShapeBorderPaint))));
  dart.setLibraryUri(container.ShapeBorderPaint, I[0]);
  dart.setFieldSignature(container.ShapeBorderPaint, () => dart.global.Object.setPrototypeOf({
    child: {type: T.Widget(), isConst: false, isFinal: true, libraryUri: I[1]},
    shape: {type: T.ShapeBorder(), isConst: false, isFinal: true, libraryUri: I[4]},
    textDirection: {type: T.TextDirectionN(), isConst: false, isFinal: true, libraryUri: I[3]},
    isForeground: {type: T.bool(), isConst: false, isFinal: true, libraryUri: I[2]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(container.ShapeBorderPaint))));
  var shape$1 = dart.privateName(container, "ShapeBorderPainter.shape");
  var textDirection$0 = dart.privateName(container, "ShapeBorderPainter.textDirection");
  var _as = dart.privateName(dart_rti, "_as");
  container.ShapeBorderPainter = class ShapeBorderPainter extends custom_paint.CustomPainter {
    get shape() {
      return this[shape$1];
    }
    set shape(value) {
      super.shape = value;
    }
    get textDirection() {
      return this[textDirection$0];
    }
    set textDirection(value) {
      super.textDirection = value;
    }
    static ['_#new#tearOff'](shape, textDirection) {
      return new container.ShapeBorderPainter.new(shape, textDirection);
    }
    paint(canvas, size) {
      this.shape.paint(canvas, ui.Offset.zero['&'](size), {textDirection: this.textDirection});
    }
    shouldRepaint(oldDelegate) {
      T.ShapeBorderPainter()[_as](oldDelegate);
      return !dart.equals(oldDelegate.shape, this.shape);
    }
  };
  (container.ShapeBorderPainter.new = function(shape, textDirection) {
    this[shape$1] = shape;
    this[textDirection$0] = textDirection;
    dart.global.Object.getPrototypeOf(container.ShapeBorderPainter).new.call(this);
    ;
  }).prototype = container.ShapeBorderPainter.prototype;
  dart.addTypeTests(container.ShapeBorderPainter);
  dart.addRtiResources(container.ShapeBorderPainter, ["flexi_chip__src__container|ShapeBorderPainter"]);
  dart.addTypeCaches(container.ShapeBorderPainter);
  dart.setMethodSignature(container.ShapeBorderPainter, () => dart.global.Object.setPrototypeOf({
    paint: T.CanvasAndSizeTovoid(),
    shouldRepaint: T.ObjectNTobool()
  }, dart.getMethods(dart.global.Object.getPrototypeOf(container.ShapeBorderPainter))));
  dart.setLibraryUri(container.ShapeBorderPainter, I[0]);
  dart.setFieldSignature(container.ShapeBorderPainter, () => dart.global.Object.setPrototypeOf({
    shape: {type: T.ShapeBorder(), isConst: false, isFinal: true, libraryUri: I[4]},
    textDirection: {type: T.TextDirectionN(), isConst: false, isFinal: true, libraryUri: I[3]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(container.ShapeBorderPainter))));
  dart.moduleConstCaches.set("packages/flexi_chip/src/container.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"flutter__src__widgets__framework|Widget":{"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__foundation__diagnostics|DiagnosticableTree":{"flutter__src__foundation__diagnostics|Diagnosticable":[]},"core|double":{"core|num":[],"Comparable.T":"core|num","core|Comparable":["core|num"]},"core|num":{"Comparable.T":"core|num","core|Comparable":["core|num"]},"core|Comparable":{"Comparable.T":"1"},"ui|Clip":{"core|_Enum":[],"core|Enum":[]},"core|_Enum":{"core|Enum":[]},"ui|TextDirection":{"core|_Enum":[],"core|Enum":[]},"flexi_chip__src__container|ShapeBorderPainter":{"flutter__src__rendering__custom_paint|CustomPainter":[],"flutter__src__foundation__change_notifier|Listenable":[]},"flutter__src__rendering__custom_paint|CustomPainter":{"flutter__src__foundation__change_notifier|Listenable":[]},"ui|Size":{"ui|OffsetBase":[]},"flexi_chip__src__container|ChipContainer":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__widgets__framework|StatelessWidget":{"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flexi_chip__src__container|ShapeBorderPaint":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]}}'));
  dart.trackLibraries("packages/flexi_chip/src/container.dart", {
    "package:flexi_chip/src/container.dart": container
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["container.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;IAce;;;;;;IACA;;;;;;IACA;;;;;;IACD;;;;;;IACC;;;;;;IACM;;;;;;IACR;;;;;;;;;;;;;;;;;UAGe;AAClB,0BAA+B,6BAAQ,OAAO;AAC9C,0BAAgB,AAAM,qBACtB,OACA,qDACiB,aAAa,SAChB,eAAL;AAGR,qBAAW,gCACR,oBACD;AAGT,UAAI;AACF,mBAAW,2CACG,eAAL,4BACQ,aAAa,SACrB,QAAQ;;AAInB,UAAI,AAAM;AACR,cAAO,kCACI,aAAa,gBACR,0BACP,QAAQ;;AAInB,UAAI,AAAM;AACR,cAAO,qCACO,eAAL,wBACI,6BACE,gCACC,0BACP,QAAQ;;AAInB,YAAO,qCACO,eAAL,wBACI,6BACE,gCACC,4BACQ,eAAb,aAAa,UACf,QAAQ;IAEnB;;;QAnEO;QACS;QACA;QACT;QACA;QACA;QACA;QACA;;IANS;IACA;IACT;IACA;IACA;IACA;IACA;AACF,oFAAW,GAAG;;EAAC;;;;;;;;;;;;;;;;;;;;IAuEP;;;;;;IACK;;;;;;IACG;;;;;;IACV;;;;;;;;;;;;;;UAGe;AAClB,oBAAU,qCAAmB,YAAO;AAC1C,YAAO,qCACI,oBAAe,OAAO,OAAO,qBACnB,oBAAe,OAAO,GAAG,aACrC;IAEX;;;QApBO;QACS;QACA;QACT;QACA;;IAHS;IACA;IACT;IACA;AACF,uFAAW,GAAG;;EAAC;;;;;;;;;;;;;;;;IAoBF;;;;;;IACG;;;;;;;;;UAGH,QAAa;AACvB,MAAN,iBAAY,MAAM,EAAS,AAAK,oBAAE,IAAI,mBAAiB;IACzD;kBAGsC;;AACpC,YAAyB,cAAlB,AAAY,WAAD,QAAU;IAC9B;;+CAZwB,OAAY;IAAZ;IAAY;AAApC;;EAAkD","file":"../../../../../../../../packages/flexi_chip/src/container.dart.lib.js"}');
  // Exports:
  return {
    src__container: container
  };
}));

//# sourceMappingURL=container.dart.lib.js.map
