// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/leak_tracker/src/devtools_integration/delivery.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/leak_tracker/src/devtools_integration/_protocol.dart', 'packages/leak_tracker/src/shared/_formatting.dart'], (function load__packages__leak_tracker__src__devtools_integration__delivery_dart(dart_sdk, packages__leak_tracker__src__devtools_integration___protocol$46dart, packages__leak_tracker__src__shared___formatting$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const convert = dart_sdk.convert;
  const _js_helper = dart_sdk._js_helper;
  const developer = dart_sdk.developer;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const _protocol = packages__leak_tracker__src__devtools_integration___protocol$46dart.src__devtools_integration___protocol;
  const _formatting = packages__leak_tracker__src__shared___formatting$46dart.src__shared___formatting;
  var delivery = Object.create(dart.library);
  var $_get = dartx._get;
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T$ = {
    String: () => (T$.String = dart.constFn(dart_rti.findType("core|String")))(),
    MapOfString$ObjectN: () => (T$.MapOfString$ObjectN = dart.constFn(dart_rti.findType("core|Map<core|String,core|Object?>")))(),
    VoidToMapOfString$String: () => (T$.VoidToMapOfString$String = dart.constFn(dart_rti.findType("core|Map<core|String,core|String>()")))(),
    ObjectNToString: () => (T$.ObjectNToString = dart.constFn(dart_rti.findType("core|String(core|Object?)")))(),
    VoidToServiceExtensionResponse: () => (T$.VoidToServiceExtensionResponse = dart.constFn(dart_rti.findType("developer|ServiceExtensionResponse()")))(),
    VoidToMapOfString$dynamic: () => (T$.VoidToMapOfString$dynamic = dart.constFn(dart_rti.findType("core|Map<core|String,@>()")))(),
    MapOfString$dynamic: () => (T$.MapOfString$dynamic = dart.constFn(dart_rti.findType("core|Map<core|String,@>")))(),
    Object: () => (T$.Object = dart.constFn(dart_rti.findType("core|Object")))(),
    EventToEventFromAppNOfObject: () => (T$.EventToEventFromAppNOfObject = dart.constFn(dart_rti.findType("leak_tracker__src__devtools_integration__delivery|EventFromApp<core|Object>?(vm_service__src__vm_service|Event)")))(),
    VoidTovoid: () => (T$.VoidTovoid = dart.constFn(dart_rti.findType("~()")))()
  };
  var G = {
    IdentityMapOfString$String: () => (G.IdentityMapOfString$String = dart.constFn(_js_helper.IdentityMap$(T$.String(), T$.String())))(),
    EventFromAppOfObject: () => (G.EventFromAppOfObject = dart.constFn(delivery.EventFromApp$(T$.Object())))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.fn(_formatting.contextToString, T$.ObjectNToString());
    }
  }, false);
  var C = [void 0];
  var I = [
    "package:leak_tracker/src/devtools_integration/delivery.dart",
    "dart:core"
  ];
  delivery._JsonFields = class _JsonFields extends core.Object {
    static ['_#new#tearOff']() {
      return new delivery._JsonFields.new();
    }
  };
  (delivery._JsonFields.new = function() {
    ;
  }).prototype = delivery._JsonFields.prototype;
  dart.addTypeTests(delivery._JsonFields);
  dart.addRtiResources(delivery._JsonFields, ["leak_tracker__src__devtools_integration__delivery|_JsonFields"]);
  dart.addTypeCaches(delivery._JsonFields);
  dart.setLibraryUri(delivery._JsonFields, I[0]);
  dart.setStaticFieldSignature(delivery._JsonFields, () => ['content']);
  dart.defineLazy(delivery._JsonFields, {
    /*delivery._JsonFields.content*/get content() {
      return "content";
    }
  }, false);
  var message$ = dart.privateName(delivery, "RequestToApp.message");
  var _eval = dart.privateName(dart_rti, "_eval");
  var _as = dart.privateName(dart_rti, "_as");
  const _is_RequestToApp_default = Symbol('_is_RequestToApp_default');
  delivery.RequestToApp$ = dart.generic(T => {
    var __t$RequestToAppOfT = () => (__t$RequestToAppOfT = dart.constFn(T[_eval]("leak_tracker__src__devtools_integration__delivery|RequestToApp<0>")))();
    class RequestToApp extends core.Object {
      get message() {
        return this[message$];
      }
      set message(value) {
        super.message = value;
      }
      static ['_#new#tearOff'](T, message) {
        return new (delivery.RequestToApp$(T)).new(message);
      }
      static ['_#fromRequestParameters#tearOff'](T, parameters) {
        return new (delivery.RequestToApp$(T)).fromRequestParameters(parameters);
      }
      toRequestParameters() {
        return new (G.IdentityMapOfString$String()).from(["content", convert.jsonEncode(_protocol.sealEnvelope(this.message, _protocol.Channel.requestToApp))]);
      }
    }
    (RequestToApp.new = function(message) {
      this[message$] = message;
      this.$ti = this.$ti || __t$RequestToAppOfT();
      ;
    }).prototype = RequestToApp.prototype;
    (RequestToApp.fromRequestParameters = function(parameters) {
      this[message$] = _protocol.openEnvelope(T, T$.MapOfString$ObjectN()[_as](convert.jsonDecode(dart.nullCheck(parameters[$_get]("content")))), _protocol.Channel.requestToApp);
      this.$ti = this.$ti || __t$RequestToAppOfT();
      ;
    }).prototype = RequestToApp.prototype;
    dart.addTypeTests(RequestToApp);
    RequestToApp.prototype[_is_RequestToApp_default] = true;
    dart.addRtiResources(RequestToApp, ["leak_tracker__src__devtools_integration__delivery|RequestToApp"]);
    dart.addTypeCaches(RequestToApp);
    dart.setMethodSignature(RequestToApp, () => dart.global.Object.setPrototypeOf({toRequestParameters: T$.VoidToMapOfString$String()}, dart.getMethods(dart.global.Object.getPrototypeOf(RequestToApp))));
    dart.setLibraryUri(RequestToApp, I[0]);
    dart.setFieldSignature(RequestToApp, () => dart.global.Object.setPrototypeOf({message: {type: T, isConst: false, isFinal: true}}, dart.getFields(dart.global.Object.getPrototypeOf(RequestToApp))));
    return RequestToApp;
  });
  delivery.RequestToApp = delivery.RequestToApp$();
  dart.addTypeTests(delivery.RequestToApp, _is_RequestToApp_default);
  var message$0 = dart.privateName(delivery, "ResponseFromApp.message");
  const _is_ResponseFromApp_default = Symbol('_is_ResponseFromApp_default');
  delivery.ResponseFromApp$ = dart.generic(T => {
    var __t$ResponseFromAppOfT = () => (__t$ResponseFromAppOfT = dart.constFn(T[_eval]("leak_tracker__src__devtools_integration__delivery|ResponseFromApp<0>")))();
    class ResponseFromApp extends core.Object {
      get message() {
        return this[message$0];
      }
      set message(value) {
        super.message = value;
      }
      static ['_#new#tearOff'](T, message) {
        return new (delivery.ResponseFromApp$(T)).new(message);
      }
      static ['_#fromJson#tearOff'](T, json) {
        return new (delivery.ResponseFromApp$(T)).fromJson(json);
      }
      static ['_#fromServiceResponse#tearOff'](T, response) {
        return new (delivery.ResponseFromApp$(T)).fromServiceResponse(response);
      }
      toServiceResponse() {
        return new developer.ServiceExtensionResponse.result(convert.jsonEncode(this.toJson(), {toEncodable: C[0] || CT.C0}));
      }
      toJson() {
        return _protocol.sealEnvelope(this.message, _protocol.Channel.responseFromApp);
      }
    }
    (ResponseFromApp.new = function(message) {
      this[message$0] = message;
      this.$ti = this.$ti || __t$ResponseFromAppOfT();
      ;
    }).prototype = ResponseFromApp.prototype;
    (ResponseFromApp.fromJson = function(json) {
      ResponseFromApp.new.call(this, _protocol.openEnvelope(T, json, _protocol.Channel.responseFromApp));
    }).prototype = ResponseFromApp.prototype;
    (ResponseFromApp.fromServiceResponse = function(response) {
      ResponseFromApp.fromJson.call(this, dart.nullCheck(response.json));
    }).prototype = ResponseFromApp.prototype;
    dart.addTypeTests(ResponseFromApp);
    ResponseFromApp.prototype[_is_ResponseFromApp_default] = true;
    dart.addRtiResources(ResponseFromApp, ["leak_tracker__src__devtools_integration__delivery|ResponseFromApp"]);
    dart.addTypeCaches(ResponseFromApp);
    dart.setMethodSignature(ResponseFromApp, () => dart.global.Object.setPrototypeOf({
      toServiceResponse: T$.VoidToServiceExtensionResponse(),
      toJson: T$.VoidToMapOfString$dynamic()
    }, dart.getMethods(dart.global.Object.getPrototypeOf(ResponseFromApp))));
    dart.setLibraryUri(ResponseFromApp, I[0]);
    dart.setFieldSignature(ResponseFromApp, () => dart.global.Object.setPrototypeOf({message: {type: T, isConst: false, isFinal: true}}, dart.getFields(dart.global.Object.getPrototypeOf(ResponseFromApp))));
    return ResponseFromApp;
  });
  delivery.ResponseFromApp = delivery.ResponseFromApp$();
  dart.addTypeTests(delivery.ResponseFromApp, _is_ResponseFromApp_default);
  var message$1 = dart.privateName(delivery, "EventFromApp.message");
  const _is_EventFromApp_default = Symbol('_is_EventFromApp_default');
  delivery.EventFromApp$ = dart.generic(T => {
    var __t$EventFromAppOfT = () => (__t$EventFromAppOfT = dart.constFn(T[_eval]("leak_tracker__src__devtools_integration__delivery|EventFromApp<0>")))();
    class EventFromApp extends core.Object {
      get message() {
        return this[message$1];
      }
      set message(value) {
        super.message = value;
      }
      static ['_#new#tearOff'](T, message) {
        return new (delivery.EventFromApp$(T)).new(message);
      }
      static ['_#fromJson#tearOff'](T, json) {
        return new (delivery.EventFromApp$(T)).fromJson(json);
      }
      static fromVmServiceEvent(event) {
        if (event.extensionKind !== "ext.dart.memoryLeakTracking") return null;
        let data = T$.MapOfString$dynamic()[_as](dart.nullCheck(event.json)[$_get]("extensionData"));
        return new (G.EventFromAppOfObject()).fromJson(data);
      }
      messageAsJson() {
        return _protocol.sealEnvelope(this.message, _protocol.Channel.eventFromApp);
      }
      post() {
        developer.postEvent("ext.dart.memoryLeakTracking", this.messageAsJson());
      }
    }
    (EventFromApp.new = function(message) {
      this[message$1] = message;
      this.$ti = this.$ti || __t$EventFromAppOfT();
      ;
    }).prototype = EventFromApp.prototype;
    (EventFromApp.fromJson = function(json) {
      EventFromApp.new.call(this, _protocol.openEnvelope(T, json, _protocol.Channel.eventFromApp));
    }).prototype = EventFromApp.prototype;
    dart.addTypeTests(EventFromApp);
    EventFromApp.prototype[_is_EventFromApp_default] = true;
    dart.addRtiResources(EventFromApp, ["leak_tracker__src__devtools_integration__delivery|EventFromApp"]);
    dart.addTypeCaches(EventFromApp);
    dart.setMethodSignature(EventFromApp, () => dart.global.Object.setPrototypeOf({
      messageAsJson: T$.VoidToMapOfString$dynamic(),
      post: T$.VoidTovoid()
    }, dart.getMethods(dart.global.Object.getPrototypeOf(EventFromApp))));
    dart.setStaticMethodSignature(EventFromApp, () => ['fromVmServiceEvent']);
    dart.setLibraryUri(EventFromApp, I[0]);
    dart.setFieldSignature(EventFromApp, () => dart.global.Object.setPrototypeOf({message: {type: T, isConst: false, isFinal: true}}, dart.getFields(dart.global.Object.getPrototypeOf(EventFromApp))));
    return EventFromApp;
  });
  delivery.EventFromApp = delivery.EventFromApp$();
  dart.addTypeTests(delivery.EventFromApp, _is_EventFromApp_default);
  dart.moduleConstCaches.set("packages/leak_tracker/src/devtools_integration/delivery.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"leak_tracker__src__devtools_integration__delivery|RequestToApp":{"RequestToApp.T":"1"},"core|Map":{"Map.K":"1","Map.V":"2"},"leak_tracker__src__devtools_integration__delivery|ResponseFromApp":{"ResponseFromApp.T":"1"},"leak_tracker__src__devtools_integration__delivery|EventFromApp":{"EventFromApp.T":"1"},"vm_service__src__vm_service|Event":{"vm_service__src__vm_service|Response":[]}}'));
  dart.trackLibraries("packages/leak_tracker/src/devtools_integration/delivery.dart", {
    "package:leak_tracker/src/devtools_integration/delivery.dart": delivery
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["delivery.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;EAgBA;;;;;;;MADsB,4BAAO;;;;;;;;;;;MAmBnB;;;;;;;;;;;;;AANN,cAAO,uDAED,mBAAW,uBAAa,cAAiB;MAEjD;;;MAbkB;;;IAAQ;mDAE6B;MACzC,iBAAE,0BACqC,8BAA7C,mBAA0C,eAA/B,AAAU,UAAA,uBACb;;;IACT;;;;;;;;;;;;;;;;;MAqBC;;;;;;;;;;;;;;;;AAGJ,cAAyB,+CACvB,mBAAW;MACZ;;AAGD,sCAAa,cAAiB;MAAgB;;;MAhB7B;;;IAAQ;yCAEiB;qCACnC,0BAAgB,IAAI,EAAU;IAAiB;oDAEb;0CACZ,eAAb,AAAS,QAAD;IAAO;;;;;;;;;;;;;;;;;;;;MAyB3B;;;;;;;;;;;;gCANsC;AAC5C,YAAI,AAAM,KAAD,kDAAmD,MAAO;AAC7D,mBAAoC,8BAAnB,AAAC,eAAX,AAAM,KAAD,cAAO;AACzB,cAAoB,yCAAS,IAAI;MACnC;;AAKI,sCAAa,cAAiB;MAAa;;AAG7C,2DAEE;MAEJ;;;MArBkB;;;IAAQ;sCAEiB;kCAChC,0BAAgB,IAAI,EAAU;IAAc","file":"../../../../../../../../../packages/leak_tracker/src/devtools_integration/delivery.dart.lib.js"}');
  // Exports:
  return {
    src__devtools_integration__delivery: delivery
  };
}));

//# sourceMappingURL=delivery.dart.lib.js.map
