// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/test_api/src/backend/live_test_controller.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/test_api/src/backend/state.dart', 'packages/stack_trace/src/stack_zone_specification.dart', 'packages/test_api/src/backend/suite.dart'], (function load__packages__test_api__src__backend__live_test_controller_dart(dart_sdk, packages__test_api__src__backend__state$46dart, packages__stack_trace__src__stack_zone_specification$46dart, packages__test_api__src__backend__suite$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const _interceptors = dart_sdk._interceptors;
  const async = dart_sdk.async;
  const collection = dart_sdk.collection;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const state = packages__test_api__src__backend__state$46dart.src__backend__state;
  const chain = packages__stack_trace__src__stack_zone_specification$46dart.src__chain;
  const live_test = packages__test_api__src__backend__suite$46dart.src__backend__live_test;
  var live_test_controller = Object.create(dart.library);
  var $add = dartx.add;
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    AsyncError: () => (T.AsyncError = dart.constFn(dart_rti.findType("async|AsyncError")))(),
    State: () => (T.State = dart.constFn(dart_rti.findType("test_api__src__backend__state|State")))(),
    Message: () => (T.Message = dart.constFn(dart_rti.findType("test_api__src__backend__message|Message")))(),
    void: () => (T.void = dart.constFn(dart_rti.findType("~")))(),
    Group: () => (T.Group = dart.constFn(dart_rti.findType("test_api__src__backend__group|Group")))(),
    LiveTest: () => (T.LiveTest = dart.constFn(dart_rti.findType("test_api__src__backend__live_test|LiveTest")))(),
    ListOfAsyncError: () => (T.ListOfAsyncError = dart.constFn(dart_rti.findType("core|List<async|AsyncError>")))(),
    StreamOfState: () => (T.StreamOfState = dart.constFn(dart_rti.findType("async|Stream<test_api__src__backend__state|State>")))(),
    StreamOfAsyncError: () => (T.StreamOfAsyncError = dart.constFn(dart_rti.findType("async|Stream<async|AsyncError>")))(),
    StreamOfMessage: () => (T.StreamOfMessage = dart.constFn(dart_rti.findType("async|Stream<test_api__src__backend__message|Message>")))(),
    bool: () => (T.bool = dart.constFn(dart_rti.findType("core|bool")))(),
    ObjectAndStackTraceNTovoid: () => (T.ObjectAndStackTraceNTovoid = dart.constFn(dart_rti.findType("~(core|Object,core|StackTrace?)")))(),
    StateTovoid: () => (T.StateTovoid = dart.constFn(dart_rti.findType("~(test_api__src__backend__state|State)")))(),
    MessageTovoid: () => (T.MessageTovoid = dart.constFn(dart_rti.findType("~(test_api__src__backend__message|Message)")))(),
    VoidToFutureOfvoid: () => (T.VoidToFutureOfvoid = dart.constFn(dart_rti.findType("async|Future<~>()")))(),
    FutureOfvoid: () => (T.FutureOfvoid = dart.constFn(dart_rti.findType("async|Future<~>")))(),
    Suite: () => (T.Suite = dart.constFn(dart_rti.findType("test_api__src__backend__suite|Suite")))(),
    ListOfGroup: () => (T.ListOfGroup = dart.constFn(dart_rti.findType("core|List<test_api__src__backend__group|Group>")))(),
    Test: () => (T.Test = dart.constFn(dart_rti.findType("test_api__src__backend__test|Test")))(),
    VoidTovoid: () => (T.VoidTovoid = dart.constFn(dart_rti.findType("~()")))(),
    StreamControllerOfState: () => (T.StreamControllerOfState = dart.constFn(dart_rti.findType("async|StreamController<test_api__src__backend__state|State>")))(),
    StreamControllerOfAsyncError: () => (T.StreamControllerOfAsyncError = dart.constFn(dart_rti.findType("async|StreamController<async|AsyncError>")))(),
    StreamControllerOfMessage: () => (T.StreamControllerOfMessage = dart.constFn(dart_rti.findType("async|StreamController<test_api__src__backend__message|Message>")))(),
    CompleterOfvoid: () => (T.CompleterOfvoid = dart.constFn(dart_rti.findType("async|Completer<~>")))()
  };
  var G = {
    JSArrayOfAsyncError: () => (G.JSArrayOfAsyncError = dart.constFn(_interceptors.JSArray$(T.AsyncError())))(),
    StreamControllerOfState: () => (G.StreamControllerOfState = dart.constFn(async.StreamController$(T.State())))(),
    StreamControllerOfAsyncError: () => (G.StreamControllerOfAsyncError = dart.constFn(async.StreamController$(T.AsyncError())))(),
    StreamControllerOfMessage: () => (G.StreamControllerOfMessage = dart.constFn(async.StreamController$(T.Message())))(),
    CompleterOfvoid: () => (G.CompleterOfvoid = dart.constFn(async.Completer$(T.void())))(),
    JSArrayOfGroup: () => (G.JSArrayOfGroup = dart.constFn(_interceptors.JSArray$(T.Group())))(),
    ListOfGroup: () => (G.ListOfGroup = dart.constFn(core.List$(T.Group())))(),
    UnmodifiableListViewOfAsyncError: () => (G.UnmodifiableListViewOfAsyncError = dart.constFn(collection.UnmodifiableListView$(T.AsyncError())))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [_Enum__name]: "success",
        [_Enum_index]: 0
      }, state.Result.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [_Enum__name]: "pending",
        [_Enum_index]: 0
      }, state.Status.prototype));
    },
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [State_result]: C[1] || CT.C1,
        [State_status]: C[2] || CT.C2
      }, state.State.prototype));
    }
  }, false);
  var C = Array(3).fill(void 0);
  var I = [
    "package:test_api/src/backend/live_test_controller.dart",
    "package:test_api/src/backend/suite.dart",
    "dart:core",
    "package:test_api/src/backend/test.dart",
    "package:test_api/src/backend/state.dart",
    "dart:async"
  ];
  var suite$ = dart.privateName(live_test_controller, "LiveTestController.suite");
  var groups$ = dart.privateName(live_test_controller, "LiveTestController.groups");
  var test$ = dart.privateName(live_test_controller, "LiveTestController.test");
  var state$ = dart.privateName(live_test_controller, "LiveTestController.state");
  var completer = dart.privateName(live_test_controller, "LiveTestController.completer");
  var _errors = dart.privateName(live_test_controller, "_errors");
  var _Enum__name = dart.privateName(core, "_Enum._name");
  var _Enum_index = dart.privateName(core, "_Enum.index");
  var State_result = dart.privateName(state, "State.result");
  var State_status = dart.privateName(state, "State.status");
  var _onStateChange = dart.privateName(live_test_controller, "_onStateChange");
  var _onError = dart.privateName(live_test_controller, "_onError");
  var _onMessage = dart.privateName(live_test_controller, "_onMessage");
  var _runCalled = dart.privateName(live_test_controller, "_runCalled");
  var _onRun$ = dart.privateName(live_test_controller, "_onRun");
  var _onClose$ = dart.privateName(live_test_controller, "_onClose");
  var _isClosed = dart.privateName(live_test_controller, "_isClosed");
  live_test_controller.LiveTestController = class LiveTestController extends live_test.LiveTest {
    get suite() {
      return this[suite$];
    }
    set suite(value) {
      super.suite = value;
    }
    get groups() {
      return this[groups$];
    }
    set groups(value) {
      super.groups = value;
    }
    get test() {
      return this[test$];
    }
    set test(value) {
      super.test = value;
    }
    get state() {
      return this[state$];
    }
    set state(value) {
      this[state$] = value;
    }
    get completer() {
      return this[completer];
    }
    set completer(value) {
      super.completer = value;
    }
    get liveTest() {
      return this;
    }
    get errors() {
      return new (G.UnmodifiableListViewOfAsyncError()).new(this[_errors]);
    }
    get onStateChange() {
      return this[_onStateChange].stream;
    }
    get onError() {
      return this[_onError].stream;
    }
    get onMessage() {
      return this[_onMessage].stream;
    }
    get [_isClosed]() {
      return this[_onError].isClosed;
    }
    static ['_#new#tearOff'](suite, test, _onRun, _onClose, opts) {
      let groups = opts && 'groups' in opts ? opts.groups : null;
      return new live_test_controller.LiveTestController.new(suite, test, _onRun, _onClose, {groups: groups});
    }
    addError(error, stackTrace) {
      let t$360;
      if (this[_isClosed]) return;
      let asyncError = new async.AsyncError.new(error, chain.Chain.forTrace((t$360 = stackTrace, t$360 == null ? new core._StringStackTrace.new("") : t$360)));
      this[_errors][$add](asyncError);
      this[_onError].add(asyncError);
    }
    setState(newState) {
      if (this[_isClosed]) return;
      if (dart.equals(this.state, newState)) return;
      this.state = newState;
      this[_onStateChange].add(newState);
    }
    message(message) {
      if (this[_onMessage].hasListener) {
        this[_onMessage].add(message);
      } else {
        async.Zone.root.print(message.text);
      }
    }
    run() {
      if (this[_runCalled]) {
        dart.throw(new core.StateError.new("LiveTest.run() may not be called more than once."));
      } else if (this[_isClosed]) {
        dart.throw(new core.StateError.new("LiveTest.run() may not be called for a closed test."));
      }
      this[_runCalled] = true;
      this[_onRun$]();
      return this.onComplete;
    }
    get onComplete() {
      return this.completer.future;
    }
    close() {
      if (this[_isClosed]) return this.onComplete;
      this[_onStateChange].close();
      this[_onError].close();
      if (this[_runCalled]) {
        this[_onClose$]();
      } else {
        this.completer.complete();
      }
      return this.onComplete;
    }
  };
  (live_test_controller.LiveTestController.new = function(suite, test, _onRun, _onClose, opts) {
    let groups = opts && 'groups' in opts ? opts.groups : null;
    this[_errors] = G.JSArrayOfAsyncError().of([]);
    this[state$] = C[0] || CT.C0;
    this[_onStateChange] = G.StreamControllerOfState().broadcast({sync: true});
    this[_onError] = G.StreamControllerOfAsyncError().broadcast({sync: true});
    this[_onMessage] = G.StreamControllerOfMessage().broadcast({sync: true});
    this[completer] = G.CompleterOfvoid().new();
    this[_runCalled] = false;
    this[suite$] = suite;
    this[test$] = test;
    this[_onRun$] = _onRun;
    this[_onClose$] = _onClose;
    this[groups$] = groups == null ? G.JSArrayOfGroup().of([suite.group]) : G.ListOfGroup().unmodifiable(groups);
    ;
  }).prototype = live_test_controller.LiveTestController.prototype;
  dart.addTypeTests(live_test_controller.LiveTestController);
  dart.addRtiResources(live_test_controller.LiveTestController, ["test_api__src__backend__live_test_controller|LiveTestController"]);
  dart.addTypeCaches(live_test_controller.LiveTestController);
  dart.setMethodSignature(live_test_controller.LiveTestController, () => dart.global.Object.setPrototypeOf({
    addError: T.ObjectAndStackTraceNTovoid(),
    setState: T.StateTovoid(),
    message: T.MessageTovoid(),
    run: T.VoidToFutureOfvoid(),
    close: T.VoidToFutureOfvoid()
  }, dart.getMethods(dart.global.Object.getPrototypeOf(live_test_controller.LiveTestController))));
  dart.setGetterSignature(live_test_controller.LiveTestController, () => dart.global.Object.setPrototypeOf({
    liveTest: T.LiveTest(),
    errors: T.ListOfAsyncError(),
    onStateChange: T.StreamOfState(),
    onError: T.StreamOfAsyncError(),
    onMessage: T.StreamOfMessage(),
    [_isClosed]: T.bool(),
    onComplete: T.FutureOfvoid()
  }, dart.getGetters(dart.global.Object.getPrototypeOf(live_test_controller.LiveTestController))));
  dart.setLibraryUri(live_test_controller.LiveTestController, I[0]);
  dart.setFieldSignature(live_test_controller.LiveTestController, () => dart.global.Object.setPrototypeOf({
    suite: {type: T.Suite(), isConst: false, isFinal: true, libraryUri: I[1]},
    groups: {type: T.ListOfGroup(), isConst: false, isFinal: true, libraryUri: I[2]},
    test: {type: T.Test(), isConst: false, isFinal: true, libraryUri: I[3]},
    [_onRun$]: {type: T.VoidTovoid(), isConst: false, isFinal: true},
    [_onClose$]: {type: T.VoidTovoid(), isConst: false, isFinal: true},
    [_errors]: {type: T.ListOfAsyncError(), isConst: false, isFinal: true, libraryUri: I[2]},
    state: {type: T.State(), isConst: false, isFinal: false, libraryUri: I[4]},
    [_onStateChange]: {type: T.StreamControllerOfState(), isConst: false, isFinal: true, libraryUri: I[5]},
    [_onError]: {type: T.StreamControllerOfAsyncError(), isConst: false, isFinal: true, libraryUri: I[5]},
    [_onMessage]: {type: T.StreamControllerOfMessage(), isConst: false, isFinal: true, libraryUri: I[5]},
    completer: {type: T.CompleterOfvoid(), isConst: false, isFinal: true, libraryUri: I[5]},
    [_runCalled]: {type: T.bool(), isConst: false, isFinal: false, libraryUri: I[2]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(live_test_controller.LiveTestController))));
  dart.moduleConstCaches.set("packages/test_api/src/backend/live_test_controller.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"async|AsyncError":{"core|Error":[]},"test_api__src__backend__group|Group":{"test_api__src__backend__group_entry|GroupEntry":[]},"core|List":{"List.E":"1","Iterable.E":"1","core|Iterable":["1"],"_ListIterable.E":"1","core|_ListIterable":["1"],"EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"]},"core|Iterable":{"Iterable.E":"1"},"core|_ListIterable":{"_ListIterable.E":"1","EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"],"Iterable.E":"1","core|Iterable":["1"]},"_internal|EfficientLengthIterable":{"EfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"_internal|HideEfficientLengthIterable":{"HideEfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"async|Stream":{"Stream.T":"1"},"async|Future":{"Future.T":"1"},"test_api__src__backend__test|Test":{"test_api__src__backend__group_entry|GroupEntry":[]},"async|StreamController":{"StreamController.T":"1","StreamSink.S":"1","async|StreamSink":["1"],"EventSink.T":"1","async|EventSink":["1"],"StreamConsumer.S":"1","async|StreamConsumer":["1"],"Sink.T":"1","core|Sink":["1"]},"async|StreamSink":{"StreamSink.S":"1","EventSink.T":"1","async|EventSink":["1"],"StreamConsumer.S":"1","async|StreamConsumer":["1"],"Sink.T":"1","core|Sink":["1"]},"async|EventSink":{"EventSink.T":"1","Sink.T":"1","core|Sink":["1"]},"async|StreamConsumer":{"StreamConsumer.S":"1"},"core|Sink":{"Sink.T":"1"},"async|Completer":{"Completer.T":"1"},"test_api__src__backend__live_test_controller|LiveTestController":{"test_api__src__backend__live_test|LiveTest":[]}}'));
  dart.trackLibraries("packages/test_api/src/backend/live_test_controller.dart", {
    "package:test_api/src/backend/live_test_controller.dart": live_test_controller
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["live_test_controller.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;IA0Bc;;;;;;IAGM;;;;;;IAGP;;;;;;IAkBL;;;;;;IA0BA;;;;;;;AArDmB;IAAI;;AAuBE,4DAAqB;IAAQ;;AAYzB,YAAA,AAAe;IAAM;;AAQtB,YAAA,AAAS;IAAM;;AAQhB,YAAA,AAAW;IAAM;;AAQ5B,YAAA,AAAS;IAAQ;;;;;aA2BlB,OAAmB;;AACtC,UAAI,iBAAW;AAEX,uBAAa,yBACb,KAAK,EAAQ,sBAAoB,QAAX,UAAU,EAAV,gBAAyB,+BAAW;AACtD,MAAR,oBAAY,UAAU;AACb,MAAT,mBAAa,UAAU;IACzB;aAOoB;AAClB,UAAI,iBAAW;AACf,UAAU,YAAN,YAAS,QAAQ,GAAE;AAEvB,mBAAQ,QAAQ;AACD,MAAf,yBAAmB,QAAQ;IAC7B;YAGqB;AACnB,UAAI,AAAW;AACF,QAAX,qBAAe,OAAO;;AAIZ,QAAL,sBAAW,AAAQ,OAAD;;IAE3B;;AAIE,UAAI;AACF,mBAAM,wBAAW;YACZ,KAAI;AACT,mBAAM;;AAGR,yBAAa;AAEP,MAAN;AACA,YAAO;IACT;;AAM+B,YAAA,AAAU;IAAM;;AAI7C,UAAI,iBAAW,MAAO;AAEP,MAAf;AACS,MAAT;AAEA,UAAI;AACM,QAAR;;AAEU,QAAV;;AAGF,YAAO;IACT;;0DA5EwB,OAAY,MAAW,QAAa;QACtC;IA1DhB,gBAAsB;IAOtB;IAMA,uBAAiB,6CAAwC;IAQzD,iBAAW,kDAA6C;IAQxD,mBAAa,+CAA0C;IAIvD,kBAAY;IAGd,mBAAa;IAqBO;IAAY;IAAW;IAAa;IAE/C,gBAAE,AAAO,MAAD,WAAW,uBAAC,AAAM,KAAD,WAAe,6BAAa,MAAM;;EAAC","file":"../../../../../../../../../packages/test_api/src/backend/live_test_controller.dart.lib.js"}');
  // Exports:
  return {
    src__backend__live_test_controller: live_test_controller
  };
}));

//# sourceMappingURL=live_test_controller.dart.lib.js.map
