// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/boolean_selector/src/parser.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/boolean_selector/src/scanner.dart', 'packages/boolean_selector/src/token.dart', 'packages/source_span/src/span_exception.dart', 'packages/boolean_selector/src/visitor.dart'], (function load__packages__boolean_selector__src__parser_dart(dart_sdk, packages__boolean_selector__src__scanner$46dart, packages__boolean_selector__src__token$46dart, packages__source_span__src__span_exception$46dart, packages__boolean_selector__src__visitor$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const scanner = packages__boolean_selector__src__scanner$46dart.src__scanner;
  const token$ = packages__boolean_selector__src__token$46dart.src__token;
  const span_exception = packages__source_span__src__span_exception$46dart.src__span_exception;
  const ast = packages__boolean_selector__src__visitor$46dart.src__ast;
  var parser = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    IdentifierToken: () => (T.IdentifierToken = dart.constFn(dart_rti.findType("boolean_selector__src__token|IdentifierToken")))(),
    VoidToNode: () => (T.VoidToNode = dart.constFn(dart_rti.findType("boolean_selector__src__ast|Node()")))(),
    Scanner: () => (T.Scanner = dart.constFn(dart_rti.findType("boolean_selector__src__scanner|Scanner")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [TokenType_name]: "not"
      }, token$.TokenType.prototype));
    },
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [TokenType_name]: "left paren"
      }, token$.TokenType.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [TokenType_name]: "identifier"
      }, token$.TokenType.prototype));
    }
  }, false);
  var C = Array(3).fill(void 0);
  var I = [
    "package:boolean_selector/src/parser.dart",
    "package:boolean_selector/src/scanner.dart"
  ];
  var _scanner = dart.privateName(parser, "_scanner");
  var _conditional = dart.privateName(parser, "_conditional");
  var _or = dart.privateName(parser, "_or");
  var _and = dart.privateName(parser, "_and");
  var _simpleExpression = dart.privateName(parser, "_simpleExpression");
  var TokenType_name = dart.privateName(token$, "TokenType.name");
  var _as = dart.privateName(dart_rti, "_as");
  parser.Parser = class Parser extends core.Object {
    static ['_#new#tearOff'](selector) {
      return new parser.Parser.new(selector);
    }
    parse() {
      let selector = this[_conditional]();
      if (!dart.equals(this[_scanner].peek().type, token$.TokenType.endOfFile)) {
        dart.throw(new span_exception.SourceSpanFormatException.new("Expected end of input.", this[_scanner].peek().span));
      }
      return selector;
    }
    [_conditional]() {
      let condition = this[_or]();
      if (!this[_scanner].scan(token$.TokenType.questionMark)) return condition;
      let whenTrue = this[_conditional]();
      if (!this[_scanner].scan(token$.TokenType.colon)) {
        dart.throw(new span_exception.SourceSpanFormatException.new("Expected \":\".", this[_scanner].peek().span));
      }
      let whenFalse = this[_conditional]();
      return new ast.ConditionalNode.new(condition, whenTrue, whenFalse);
    }
    [_or]() {
      let left = this[_and]();
      if (!this[_scanner].scan(token$.TokenType.or)) return left;
      return new ast.OrNode.new(left, this[_or]());
    }
    [_and]() {
      let left = this[_simpleExpression]();
      if (!this[_scanner].scan(token$.TokenType.and)) return left;
      return new ast.AndNode.new(left, this[_and]());
    }
    [_simpleExpression]() {
      let token = this[_scanner].next();
      switch (token.type) {
        case C[0] || CT.C0:
          {
            let child = this[_simpleExpression]();
            return new ast.NotNode.new(child, token.span.expand(dart.nullCheck(child.span)));
          }
        case C[1] || CT.C1:
          {
            let child = this[_conditional]();
            if (!this[_scanner].scan(token$.TokenType.rightParen)) {
              dart.throw(new span_exception.SourceSpanFormatException.new("Expected \")\".", this[_scanner].peek().span));
            }
            return child;
          }
        case C[2] || CT.C2:
          {
            return new ast.VariableNode.new(T.IdentifierToken()[_as](token).name, token.span);
          }
        default:
          {
            dart.throw(new span_exception.SourceSpanFormatException.new("Expected expression.", token.span));
          }
      }
    }
  };
  (parser.Parser.new = function(selector) {
    this[_scanner] = new scanner.Scanner.new(selector);
    ;
  }).prototype = parser.Parser.prototype;
  dart.addTypeTests(parser.Parser);
  dart.addRtiResources(parser.Parser, ["boolean_selector__src__parser|Parser"]);
  dart.addTypeCaches(parser.Parser);
  dart.setMethodSignature(parser.Parser, () => dart.global.Object.setPrototypeOf({
    parse: T.VoidToNode(),
    [_conditional]: T.VoidToNode(),
    [_or]: T.VoidToNode(),
    [_and]: T.VoidToNode(),
    [_simpleExpression]: T.VoidToNode()
  }, dart.getMethods(dart.global.Object.getPrototypeOf(parser.Parser))));
  dart.setLibraryUri(parser.Parser, I[0]);
  dart.setFieldSignature(parser.Parser, () => dart.global.Object.setPrototypeOf({[_scanner]: {type: T.Scanner(), isConst: false, isFinal: true, libraryUri: I[1]}}, dart.getFields(dart.global.Object.getPrototypeOf(parser.Parser))));
  dart.moduleConstCaches.set("packages/boolean_selector/src/parser.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"boolean_selector__src__token|IdentifierToken":{"boolean_selector__src__token|Token":[]}}'));
  dart.trackLibraries("packages/boolean_selector/src/parser.dart", {
    "package:boolean_selector/src/parser.dart": parser
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["parser.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;AA0BQ,qBAAW;AAEf,uBAAI,AAAS,AAAO,4BAAkB;AACpC,mBAAM,iDACF,0BAA0B,AAAS,AAAO;;AAGhD,YAAO,SAAQ;IACjB;;AAQM,sBAAY;AAChB,WAAK,AAAS,oBAAe,gCAAe,MAAO,UAAS;AAExD,qBAAW;AACf,WAAK,AAAS,oBAAe;AAC3B,mBAAM,iDAA0B,mBAAiB,AAAS,AAAO;;AAG/D,sBAAY;AAChB,YAAO,6BAAgB,SAAS,EAAE,QAAQ,EAAE,SAAS;IACvD;;AAOM,iBAAO;AACX,WAAK,AAAS,oBAAe,sBAAK,MAAO,KAAI;AAC7C,YAAO,oBAAO,IAAI,EAAE;IACtB;;AAOM,iBAAO;AACX,WAAK,AAAS,oBAAe,uBAAM,MAAO,KAAI;AAC9C,YAAO,qBAAQ,IAAI,EAAE;IACvB;;AASM,kBAAQ,AAAS;AACrB,cAAQ,AAAM,KAAD;;;AAEL,wBAAQ;AACZ,kBAAO,qBAAQ,KAAK,EAAE,AAAM,AAAK,KAAN,aAAuB,eAAV,AAAM,KAAD;;;;AAGzC,wBAAQ;AACZ,iBAAK,AAAS,oBAAe;AAC3B,yBAAM,iDACF,mBAAiB,AAAS,AAAO;;AAEvC,kBAAO,MAAK;;;;AAGZ,kBAAO,0BAAoB,AAAoB,yBAA1B,KAAK,QAA2B,AAAM,KAAD;;;;AAG1D,uBAAM,iDAA0B,wBAAwB,AAAM,KAAD;;;IAEnE;;gCAjFc;IAAqB,iBAAE,wBAAQ,QAAQ;;EAAC","file":"../../../../../../../../packages/boolean_selector/src/parser.dart.lib.js"}');
  // Exports:
  return {
    src__parser: parser
  };
}));

//# sourceMappingURL=parser.dart.lib.js.map
