// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/matcher/src/expect/util/pretty_print.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/matcher/src/equals_matcher.dart', 'packages/term_glyph/src/generated/top_level.dart'], (function load__packages__matcher__src__expect__util__pretty_print_dart(dart_sdk, packages__matcher__src__equals_matcher$46dart, packages__term_glyph__src__generated__top_level$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const description = packages__matcher__src__equals_matcher$46dart.src__description;
  const top_level = packages__term_glyph__src__generated__top_level$46dart.src__generated__top_level;
  var pretty_print = Object.create(dart.library);
  var $times = dartx['*'];
  var $split = dartx.split;
  var $length = dartx.length;
  var $first = dartx.first;
  var $skip = dartx.skip;
  var $take = dartx.take;
  var $last = dartx.last;
  var $toString = dartx.toString;
  var $map = dartx.map;
  var $join = dartx.join;
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    String: () => (T.String = dart.constFn(dart_rti.findType("core|String")))(),
    StringToString: () => (T.StringToString = dart.constFn(dart_rti.findType("core|String(core|String)")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.fn(pretty_print.addBullet, T.StringToString());
    }
  }, false);
  var C = [void 0];
  pretty_print.indent = function indent(text, opts) {
    let first = opts && 'first' in opts ? opts.first : null;
    let prefix = " "[$times](first.length);
    let lines = text[$split]("\n");
    if (lines[$length] === 1) return first + text;
    let buffer = new core.StringBuffer.new(first + lines[$first] + "\n");
    for (let line of lines[$skip](1)[$take](lines[$length] - 2)) {
      buffer.writeln(prefix + line);
    }
    buffer.write(prefix + lines[$last]);
    return dart.toString(buffer);
  };
  pretty_print.prettyPrint = function prettyPrint(value) {
    return dart.toString(new description.StringDescription.new().addDescriptionOf(value));
  };
  pretty_print.addBullet = function addBullet(text) {
    return pretty_print.indent(text, {first: top_level.bullet + " "});
  };
  pretty_print.bullet = function bullet(strings) {
    return strings[$map](T.String(), C[0] || CT.C0)[$join]("\n");
  };
  pretty_print.pluralize = function pluralize(name, number, opts) {
    let plural = opts && 'plural' in opts ? opts.plural : null;
    if (number === 1) return name;
    if (plural != null) return plural;
    return name + "s";
  };
  dart.moduleConstCaches.set("packages/matcher/src/expect/util/pretty_print.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"}}'));
  dart.trackLibraries("packages/matcher/src/expect/util/pretty_print.dart", {
    "package:matcher/src/expect/util/pretty_print.dart": pretty_print
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["pretty_print.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;wCAWqB;QAAuB;AACpC,iBAAS,AAAI,YAAE,AAAM,KAAD;AACtB,gBAAQ,AAAK,IAAD,SAAO;AACvB,QAAI,AAAM,AAAO,KAAR,cAAW,GAAG,MAAS,AAAW,MAAN,GAAC,IAAI;AAEtC,iBAAS,0BAAe,AAAsB,KAAjB,GAAE,AAAM,KAAD,WAAO;AAG/C,aAAS,OAAQ,AAAM,AAAQ,MAAT,QAAM,UAAQ,AAAM,AAAO,KAAR,YAAU;AAC1C,MAAP,MAAM,SAAW,AAAY,MAAN,GAAC,IAAI;;AAEvB,IAAP,MAAM,OAAS,AAAoB,MAAd,GAAE,AAAM,KAAD;AAC5B,UAAc,eAAP,MAAM;EACf;kDAM2B;AACvB,UAA4C,eAA5C,AAAoB,yDAAiB,KAAK;EAAY;8CAGlC;AAAS,+BAAO,IAAI,UAAkB,AAAS,mBAAF;EAAG;wCAGzC;AAAY,UAAA,AAAQ,AAAe,QAAhB,yCAAqB;EAAK;8CAMpD,MAAU;QAAiB;AACjD,QAAI,AAAO,MAAD,KAAI,GAAG,MAAO,KAAI;AAC5B,QAAI,MAAM,UAAU,MAAO,OAAM;AACjC,UAAU,AAAO,KAAH,GAAC;EACjB","file":"../../../../../../../../../../packages/matcher/src/expect/util/pretty_print.dart.lib.js"}');
  // Exports:
  return {
    src__expect__util__pretty_print: pretty_print
  };
}));

//# sourceMappingURL=pretty_print.dart.lib.js.map
