// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/ypo_connect/profile_menu.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/flutter/src/widgets/unique_widget.dart', 'packages/flutter/src/material/colors.dart', 'packages/flutter/src/material/time.dart', 'packages/flutter/src/painting/box_decoration.dart', 'packages/flutter/src/painting/border_radius.dart', 'packages/line_awesome_flutter/line_awesome_flutter.dart'], (function load__packages__ypo_connect__profile_menu_dart(dart_sdk, packages__flutter__src__widgets__unique_widget$46dart, packages__flutter__src__material__colors$46dart, packages__flutter__src__material__time$46dart, packages__flutter__src__painting__box_decoration$46dart, packages__flutter__src__painting__border_radius$46dart, packages__line_awesome_flutter__line_awesome_flutter$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const ui = dart_sdk.ui;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const widget_inspector = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__widget_inspector;
  const media_query = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__media_query;
  const container = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__container;
  const icon = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__icon;
  const text = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__text;
  const framework = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__framework;
  const colors = packages__flutter__src__material__colors$46dart.src__material__colors;
  const list_tile = packages__flutter__src__material__time$46dart.src__material__list_tile;
  const theme = packages__flutter__src__material__time$46dart.src__material__theme;
  const box_decoration = packages__flutter__src__painting__box_decoration$46dart.src__painting__box_decoration;
  const border_radius = packages__flutter__src__painting__border_radius$46dart.src__painting__border_radius;
  const line_awesome_flutter = packages__line_awesome_flutter__line_awesome_flutter$46dart.line_awesome_flutter;
  var profile_menu = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    BuildContextToWidget: () => (T.BuildContextToWidget = dart.constFn(dart_rti.findType("flutter__src__widgets__framework|Widget(flutter__src__widgets__framework|BuildContext)")))(),
    String: () => (T.String = dart.constFn(dart_rti.findType("core|String")))(),
    IconData: () => (T.IconData = dart.constFn(dart_rti.findType("flutter__src__widgets__icon_data|IconData")))(),
    VoidTovoid: () => (T.VoidTovoid = dart.constFn(dart_rti.findType("~()")))(),
    bool: () => (T.bool = dart.constFn(dart_rti.findType("core|bool")))(),
    ColorN: () => (T.ColorN = dart.constFn(dart_rti.findType("ui|Color?")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ProfileMenuWidget",
        [_Location_column]: 9,
        [_Location_line]: 7,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Icon",
        [_Location_column]: 16,
        [_Location_line]: 37,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Container",
        [_Location_column]: 16,
        [_Location_line]: 30,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C3() {
      return C[3] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Text",
        [_Location_column]: 14,
        [_Location_line]: 39,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C4() {
      return C[4] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Icon",
        [_Location_column]: 18,
        [_Location_line]: 47,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C5() {
      return C[5] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Container",
        [_Location_column]: 26,
        [_Location_line]: 40,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    },
    get C6() {
      return C[6] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ListTile",
        [_Location_column]: 12,
        [_Location_line]: 28,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/profile_menu.dart"
      }, widget_inspector._Location.prototype));
    }
  }, false);
  var C = Array(7).fill(void 0);
  var I = [
    "package:ypo_connect/profile_menu.dart",
    "dart:core",
    "package:flutter/src/widgets/icon_data.dart",
    "dart:ui"
  ];
  var title$ = dart.privateName(profile_menu, "ProfileMenuWidget.title");
  var icon$ = dart.privateName(profile_menu, "ProfileMenuWidget.icon");
  var onPress$ = dart.privateName(profile_menu, "ProfileMenuWidget.onPress");
  var endIcon$ = dart.privateName(profile_menu, "ProfileMenuWidget.endIcon");
  var textColor$ = dart.privateName(profile_menu, "ProfileMenuWidget.textColor");
  var _Location_name = dart.privateName(widget_inspector, "_Location.name");
  var _Location_column = dart.privateName(widget_inspector, "_Location.column");
  var _Location_line = dart.privateName(widget_inspector, "_Location.line");
  var _Location_file = dart.privateName(widget_inspector, "_Location.file");
  profile_menu.ProfileMenuWidget = class ProfileMenuWidget extends framework.StatelessWidget {
    get title() {
      return this[title$];
    }
    set title(value) {
      super.title = value;
    }
    get icon() {
      return this[icon$];
    }
    set icon(value) {
      super.icon = value;
    }
    get onPress() {
      return this[onPress$];
    }
    set onPress(value) {
      super.onPress = value;
    }
    get endIcon() {
      return this[endIcon$];
    }
    set endIcon(value) {
      super.endIcon = value;
    }
    get textColor() {
      return this[textColor$];
    }
    set textColor(value) {
      super.textColor = value;
    }
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      let title = opts && 'title' in opts ? opts.title : null;
      let icon = opts && 'icon' in opts ? opts.icon : null;
      let onPress = opts && 'onPress' in opts ? opts.onPress : null;
      let endIcon = opts && 'endIcon' in opts ? opts.endIcon : false;
      let textColor = opts && 'textColor' in opts ? opts.textColor : null;
      return new profile_menu.ProfileMenuWidget.new({key: key, title: title, icon: icon, onPress: onPress, endIcon: endIcon, textColor: textColor, $creationLocationd_0dea112b090073317d4: C[0] || CT.C0});
    }
    build(context) {
      let t$360;
      let isDark = media_query.MediaQuery.of(context).platformBrightness === ui.Brightness.dark;
      let iconColor = isDark ? colors.Colors.blue : colors.Colors.greenAccent;
      return new list_tile.ListTile.new({onTap: this.onPress, leading: new container.Container.new({width: 40.0, height: 40.0, decoration: new box_decoration.BoxDecoration.new({borderRadius: new border_radius.BorderRadius.circular(100.0), color: iconColor.withOpacity(0.1)}), child: new icon.Icon.new(this.icon, {color: iconColor, $creationLocationd_0dea112b090073317d4: C[1] || CT.C1}), $creationLocationd_0dea112b090073317d4: C[2] || CT.C2}), title: new text.Text.new(this.title, {style: (t$360 = theme.Theme.of(context).textTheme.bodyText1, t$360 == null ? null : t$360.apply({color: this.textColor})), $creationLocationd_0dea112b090073317d4: C[3] || CT.C3}), trailing: this.endIcon ? new container.Container.new({width: 30.0, height: 30.0, decoration: new box_decoration.BoxDecoration.new({borderRadius: new border_radius.BorderRadius.circular(100.0), color: colors.Colors.grey.withOpacity(0.1)}), child: new icon.Icon.new(line_awesome_flutter.LineAwesomeIcons.angle_right_solid, {size: 18.0, color: colors.Colors.grey, $creationLocationd_0dea112b090073317d4: C[4] || CT.C4}), $creationLocationd_0dea112b090073317d4: C[5] || CT.C5}) : null, $creationLocationd_0dea112b090073317d4: C[6] || CT.C6});
    }
  };
  (profile_menu.ProfileMenuWidget.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let title = opts && 'title' in opts ? opts.title : null;
    let icon = opts && 'icon' in opts ? opts.icon : null;
    let onPress = opts && 'onPress' in opts ? opts.onPress : null;
    let endIcon = opts && 'endIcon' in opts ? opts.endIcon : false;
    let textColor = opts && 'textColor' in opts ? opts.textColor : null;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    this[title$] = title;
    this[icon$] = icon;
    this[onPress$] = onPress;
    this[endIcon$] = endIcon;
    this[textColor$] = textColor;
    dart.global.Object.getPrototypeOf(profile_menu.ProfileMenuWidget).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = profile_menu.ProfileMenuWidget.prototype;
  dart.addTypeTests(profile_menu.ProfileMenuWidget);
  dart.addRtiResources(profile_menu.ProfileMenuWidget, ["ypo_connect__profile_menu|ProfileMenuWidget"]);
  dart.addTypeCaches(profile_menu.ProfileMenuWidget);
  dart.setMethodSignature(profile_menu.ProfileMenuWidget, () => dart.global.Object.setPrototypeOf({build: T.BuildContextToWidget()}, dart.getMethods(dart.global.Object.getPrototypeOf(profile_menu.ProfileMenuWidget))));
  dart.setLibraryUri(profile_menu.ProfileMenuWidget, I[0]);
  dart.setFieldSignature(profile_menu.ProfileMenuWidget, () => dart.global.Object.setPrototypeOf({
    title: {type: T.String(), isConst: false, isFinal: true, libraryUri: I[1]},
    icon: {type: T.IconData(), isConst: false, isFinal: true, libraryUri: I[2]},
    onPress: {type: T.VoidTovoid(), isConst: false, isFinal: true},
    endIcon: {type: T.bool(), isConst: false, isFinal: true, libraryUri: I[1]},
    textColor: {type: T.ColorN(), isConst: false, isFinal: true, libraryUri: I[3]}
  }, dart.getFields(dart.global.Object.getPrototypeOf(profile_menu.ProfileMenuWidget))));
  dart.moduleConstCaches.set("packages/ypo_connect/profile_menu.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"flutter__src__widgets__framework|Widget":{"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__foundation__diagnostics|DiagnosticableTree":{"flutter__src__foundation__diagnostics|Diagnosticable":[]},"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"ypo_connect__profile_menu|ProfileMenuWidget":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__widgets__framework|StatelessWidget":{"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]}}'));
  dart.trackLibraries("packages/ypo_connect/profile_menu.dart", {
    "package:ypo_connect/profile_menu.dart": profile_menu
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["profile_menu.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;IAee;;;;;;IACE;;;;;;IACI;;;;;;IACR;;;;;;IACE;;;;;;;;;;;;;;;UAGa;;AAEpB,mBAAoB,AAAY,AAAmB,0BAA5B,OAAO,yBAAmC;AACjE,sBAAY,MAAM,GAAU,qBAAc,yBAAxB;AAEtB,YAAO,oCACE,uBACE,oCACA,cACC,kBACI,oDACiB,wCAAS,eAC7B,AAAU,SAAD,aAAa,eAExB,kBAAK,mBAAa,SAAS,2HAE7B,kBAAK,6BAAoB,AAAY,AAAU,eAAnB,OAAO,uCAAY,OAAW,oBAAa,sFACpE,eAAS,oCACR,cACC,kBACI,oDACiB,wCAAS,eACtB,AAAK,+BAAY,eAE1B,kBAAsB,gEAAyB,aAAoB,uIAAS;IAE3F;;;QAzCQ;QACQ;QACA;QACA;QACT;QACA;;IAJS;IACA;IACA;IACT;IACA;AAND,2FACE,GAAG;;EAMT","file":"../../../../../packages/ypo_connect/profile_menu.dart.lib.js"}');
  // Exports:
  return {
    profile_menu: profile_menu
  };
}));

//# sourceMappingURL=profile_menu.dart.lib.js.map
