// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/leak_tracker_flutter_testing/src/testing.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/leak_tracker_testing/src/leak_testing.dart', 'packages/flutter/src/foundation/_platform_web.dart', 'packages/leak_tracker/src/leak_tracking/primitives/model.dart', 'packages/leak_tracker/src/leak_tracking/leak_tracking.dart', 'packages/leak_tracker/src/shared/shared_model.dart', 'packages/flutter/src/foundation/memory_allocations.dart', 'packages/leak_tracker/src/leak_tracking/helpers.dart', 'packages/flutter/src/foundation/print.dart'], (function load__packages__leak_tracker_flutter_testing__src__testing_dart(dart_sdk, packages__leak_tracker_testing__src__leak_testing$46dart, packages__flutter__src__foundation___platform_web$46dart, packages__leak_tracker__src__leak_tracking__primitives__model$46dart, packages__leak_tracker__src__leak_tracking__leak_tracking$46dart, packages__leak_tracker__src__shared__shared_model$46dart, packages__flutter__src__foundation__memory_allocations$46dart, packages__leak_tracker__src__leak_tracking__helpers$46dart, packages__flutter__src__foundation__print$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const _js_helper = dart_sdk._js_helper;
  const async = dart_sdk.async;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const leak_testing = packages__leak_tracker_testing__src__leak_testing$46dart.src__leak_testing;
  const platform = packages__flutter__src__foundation___platform_web$46dart.src__foundation__platform;
  const model = packages__leak_tracker__src__leak_tracking__primitives__model$46dart.src__leak_tracking__primitives__model;
  const leak_tracking = packages__leak_tracker__src__leak_tracking__leak_tracking$46dart.src__leak_tracking__leak_tracking;
  const shared_model = packages__leak_tracker__src__shared__shared_model$46dart.src__shared__shared_model;
  const memory_allocations = packages__flutter__src__foundation__memory_allocations$46dart.src__foundation__memory_allocations;
  const helpers = packages__leak_tracker__src__leak_tracking__helpers$46dart.src__leak_tracking__helpers;
  const print = packages__flutter__src__foundation__print$46dart.src__foundation__print;
  var testing = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    String: () => (T.String = dart.constFn(dart_rti.findType("core|String")))(),
    intN: () => (T.intN = dart.constFn(dart_rti.findType("core|int?")))(),
    LeakType: () => (T.LeakType = dart.constFn(dart_rti.findType("leak_tracker__src__shared__shared_model|LeakType")))(),
    ListOfLeakReport: () => (T.ListOfLeakReport = dart.constFn(dart_rti.findType("core|List<leak_tracker__src__shared__shared_model|LeakReport>")))(),
    ObjectEventTovoid: () => (T.ObjectEventTovoid = dart.constFn(dart_rti.findType("~(flutter__src__foundation__memory_allocations|ObjectEvent)")))(),
    void: () => (T.void = dart.constFn(dart_rti.findType("~")))()
  };
  var G = {
    LinkedMapOfLeakType$ListOfLeakReport: () => (G.LinkedMapOfLeakType$ListOfLeakReport = dart.constFn(_js_helper.LinkedMap$(T.LeakType(), T.ListOfLeakReport())))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [LeakDiagnosticConfig_collectRetainingPathForNotGCed]: false,
        [LeakDiagnosticConfig_collectStackTraceOnDisposal]: false,
        [LeakDiagnosticConfig_collectStackTraceOnStart]: false
      }, model.LeakDiagnosticConfig.prototype));
    },
    get C4() {
      return C[4] = dart.constMap(T.String(), T.intN(), []);
    },
    get C3() {
      return C[3] = dart.const(Object.setPrototypeOf({
        [IgnoredLeaksSet_ignoreAll]: false,
        [IgnoredLeaksSet_byClass]: C[4] || CT.C4
      }, model.IgnoredLeaksSet.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [IgnoredLeaks_notDisposed]: C[3] || CT.C3,
        [IgnoredLeaks_notGCed]: C[3] || CT.C3
      }, model.IgnoredLeaks.prototype));
    },
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [PhaseSettings_baselining]: null,
        [PhaseSettings_leakDiagnosticConfig]: C[1] || CT.C1,
        [PhaseSettings_ignoredLeaks]: C[2] || CT.C2,
        [PhaseSettings_name]: null,
        [PhaseSettings_ignoreLeaks]: true
      }, model.PhaseSettings.prototype));
    },
    get C5() {
      return C[5] = dart.fn(testing._dispatchFlutterEventToLeakTracker, T.ObjectEventTovoid());
    }
  }, false);
  var C = Array(6).fill(void 0);
  var PhaseSettings_baselining = dart.privateName(model, "PhaseSettings.baselining");
  var LeakDiagnosticConfig_collectRetainingPathForNotGCed = dart.privateName(model, "LeakDiagnosticConfig.collectRetainingPathForNotGCed");
  var LeakDiagnosticConfig_collectStackTraceOnDisposal = dart.privateName(model, "LeakDiagnosticConfig.collectStackTraceOnDisposal");
  var LeakDiagnosticConfig_collectStackTraceOnStart = dart.privateName(model, "LeakDiagnosticConfig.collectStackTraceOnStart");
  var PhaseSettings_leakDiagnosticConfig = dart.privateName(model, "PhaseSettings.leakDiagnosticConfig");
  var IgnoredLeaksSet_ignoreAll = dart.privateName(model, "IgnoredLeaksSet.ignoreAll");
  var IgnoredLeaksSet_byClass = dart.privateName(model, "IgnoredLeaksSet.byClass");
  var IgnoredLeaks_notDisposed = dart.privateName(model, "IgnoredLeaks.notDisposed");
  var IgnoredLeaks_notGCed = dart.privateName(model, "IgnoredLeaks.notGCed");
  var PhaseSettings_ignoredLeaks = dart.privateName(model, "PhaseSettings.ignoredLeaks");
  var PhaseSettings_name = dart.privateName(model, "PhaseSettings.name");
  var PhaseSettings_ignoreLeaks = dart.privateName(model, "PhaseSettings.ignoreLeaks");
  testing.maybeSetupLeakTrackingForTest = function maybeSetupLeakTrackingForTest(settings, testDescription) {
    let t$360;
    if (!leak_testing.LeakTesting.enabled) return;
    let leakTesting = (t$360 = settings, t$360 == null ? leak_testing.LeakTesting.settings : t$360);
    if (leakTesting.ignore) return;
    if (!testing._checkPlatformAndMayBePrintWarning({platformName: core['EnumName|get#name'](platform.defaultTargetPlatform), isBrowser: true})) {
      return;
    }
    testing._maybeStartLeakTracking();
    let phase = new model.PhaseSettings.new({name: testDescription, leakDiagnosticConfig: leakTesting.leakDiagnosticConfig, ignoredLeaks: leakTesting.ignoredLeaks, baselining: leakTesting.baselining, ignoreLeaks: leakTesting.ignore});
    leak_tracking.LeakTracking.phase = phase;
  };
  testing.maybeTearDownLeakTrackingForTest = function maybeTearDownLeakTrackingForTest() {
    if (!leak_testing.LeakTesting.enabled || !leak_tracking.LeakTracking.isStarted || leak_tracking.LeakTracking.phase.ignoreLeaks) return;
    leak_tracking.LeakTracking.phase = C[0] || CT.C0;
  };
  testing.maybeTearDownLeakTrackingForAll = function maybeTearDownLeakTrackingForAll() {
    return async.async(T.void(), function* maybeTearDownLeakTrackingForAll() {
      if (!leak_testing.LeakTesting.enabled || !leak_tracking.LeakTracking.isStarted) {
        leak_testing.LeakTesting.collectedLeaksReporter(new shared_model.Leaks.new(new (G.LinkedMapOfLeakType$ListOfLeakReport()).new()));
        return;
      }
      memory_allocations.FlutterMemoryAllocations.instance.removeListener(C[5] || CT.C5);
      yield helpers.forceGC({fullGcCycles: 3});
      leak_tracking.LeakTracking.declareNotDisposedObjectsAsLeaks();
      let leaks = (yield leak_tracking.LeakTracking.collectLeaks());
      leak_tracking.LeakTracking.stop();
      leak_testing.LeakTesting.collectedLeaksReporter(leaks);
    });
  };
  testing._dispatchFlutterEventToLeakTracker = function _dispatchFlutterEventToLeakTracker(event) {
    return leak_tracking.LeakTracking.dispatchObjectEvent(event.toMap());
  };
  testing._checkPlatformAndMayBePrintWarning = function _checkPlatformAndMayBePrintWarning(opts) {
    let platformName = opts && 'platformName' in opts ? opts.platformName : null;
    let isBrowser = opts && 'isBrowser' in opts ? opts.isBrowser : null;
    let isSupported = !isBrowser;
    if (isSupported) return true;
    let shouldPrintWarning = leak_tracking.LeakTracking.warnForUnsupportedPlatforms && !testing._notSupportedWarningPrinted;
    if (!shouldPrintWarning) return false;
    testing._notSupportedWarningPrinted = true;
    print.debugPrint("Leak tracking is not supported on the platform '" + platformName + "'.\n" + "To turn off this message, set " + "`LeakTracking.warnForNotSupportedPlatforms` to false.");
    return false;
  };
  testing._maybeStartLeakTracking = function _maybeStartLeakTracking() {
    if (leak_tracking.LeakTracking.isStarted) return;
    leak_tracking.LeakTracking.phase = C[0] || CT.C0;
    leak_tracking.LeakTracking.start({config: new model.LeakTrackingConfig.passive()});
    memory_allocations.FlutterMemoryAllocations.instance.addListener(C[5] || CT.C5);
  };
  dart.defineLazy(testing, {
    /*testing._notSupportedWarningPrinted*/get _notSupportedWarningPrinted() {
      return false;
    },
    set _notSupportedWarningPrinted(value) {}
  }, false);
  dart.moduleConstCaches.set("packages/leak_tracker_flutter_testing/src/testing.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"core|int":{"core|num":[],"Comparable.T":"core|num","core|Comparable":["core|num"]},"core|num":{"Comparable.T":"core|num","core|Comparable":["core|num"]},"leak_tracker__src__shared__shared_model|LeakType":{"core|_Enum":[],"core|Enum":[]},"core|_Enum":{"core|Enum":[]},"core|List":{"List.E":"1","Iterable.E":"1","core|Iterable":["1"],"_ListIterable.E":"1","core|_ListIterable":["1"],"EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"]},"core|Iterable":{"Iterable.E":"1"},"core|_ListIterable":{"_ListIterable.E":"1","EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"],"Iterable.E":"1","core|Iterable":["1"]},"_internal|EfficientLengthIterable":{"EfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"_internal|HideEfficientLengthIterable":{"HideEfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]}}'));
  dart.trackLibraries("packages/leak_tracker_flutter_testing/src/testing.dart", {
    "package:leak_tracker_flutter_testing/src/testing.dart": testing
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["testing.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iFAce,UACN;;AAEP,SAAiB,kCAAS;AAEpB,uBAAuB,QAAT,QAAQ,EAAR,gBAAwB;AAC5C,QAAI,AAAY,WAAD,SAAS;AAExB,SAAK,0DACmC,0BAAtB;AAChB;;AAGF;AAEM,gBAAQ,mCACN,eAAe,wBACC,AAAY,WAAD,qCACnB,AAAY,WAAD,2BACb,AAAY,WAAD,0BACV,AAAY,WAAD;AAGb,uCAAQ,KAAK;EAC5B;;AAKE,SAAiB,qCACC,wCACD,AAAM,8CAAa;AACvB;EACf;;AAK4C;AAC1C,WAAiB,qCAAyB;AAGN,QAAtB,gDAAuB,2BAAM;AACzC;;AAKyB,MAAT;AAClB,YAAM;AACO;AACP,mBAAQ,MAAmB;AACpB;AAEqB,MAAtB,gDAAuB,KAAK;IAC1C;;2FAEoD;AAClD,UAAoB,gDAAoB,AAAM,KAAD;EAC/C;;QAUqB;QAA4B;AACzC,uBAAe,SAAS;AAE9B,QAAI,WAAW,EAAE,MAAO;AAElB,6BACW,AAA4B,2DAAI;AAEjD,SAAK,kBAAkB,EAAE,MAAO;AAEhC,0CAA8B;AACpB,IAAV,iBAAU,AACR,qDAAkD,YAAY,YAC9D,mCACA;AAGF,UAAO;EACT;;AAIE,QAAiB,sCAAW;AAEf;AACA,8CAAiC;AACnB,IAAT;EACpB;;MAnCK,mCAA2B;YAAG","file":"../../../../../../../../packages/leak_tracker_flutter_testing/src/testing.dart.lib.js"}');
  // Exports:
  return {
    src__testing: testing
  };
}));

//# sourceMappingURL=testing.dart.lib.js.map
