// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/test_api/src/scaffolding/utils.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/test_api/src/backend/declarer.dart'], (function load__packages__test_api__src__scaffolding__utils_dart(dart_sdk, packages__test_api__src__backend__declarer$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const async = dart_sdk.async;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const invoker = packages__test_api__src__backend__declarer$46dart.src__backend__invoker;
  var utils = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    VoidToFuture: () => (T.VoidToFuture = dart.constFn(dart_rti.findType("async|Future<@>()")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [_StringStackTrace__stackTrace]: ""
      }, core._StringStackTrace.prototype));
    }
  }, false);
  var C = [void 0];
  var _StringStackTrace__stackTrace = dart.privateName(core, "_StringStackTrace._stackTrace");
  utils.pumpEventQueue = function pumpEventQueue(opts) {
    let times = opts && 'times' in opts ? opts.times : 20;
    if (times === 0) return async.Future.value();
    return async.Future.new(dart.fn(() => utils.pumpEventQueue({times: times - 1}), T.VoidToFuture()));
  };
  utils.registerException = function registerException(error, stackTrace = C[0] || CT.C0) {
    async.Zone.current.handleUncaughtError(error, stackTrace);
  };
  utils.printOnFailure = function printOnFailure(message) {
    utils._currentInvoker.printOnFailure(message);
  };
  utils.markTestSkipped = function markTestSkipped(message) {
    let t$360;
    t$360 = utils._currentInvoker;
    return (() => {
      t$360.skip(message);
      return t$360;
    })();
  };
  dart.copyProperties(utils, {
    get _currentInvoker() {
      let t$360;
      t$360 = invoker.Invoker.current;
      return t$360 == null ? dart.throw(new core.StateError.new("There is no current invoker. Please make sure that you are making the call inside a test zone.")) : t$360;
    }
  });
  dart.moduleConstCaches.set("packages/test_api/src/scaffolding/utils.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"async|Future":{"Future.T":"1"}}'));
  dart.trackLibraries("packages/test_api/src/scaffolding/utils.dart", {
    "package:test_api/src/scaffolding/utils.dart": utils
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["utils.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;QAe2B;AACzB,QAAI,AAAM,KAAD,KAAI,GAAG,MAAc;AAE9B,UAAO,kBAAO,cAAM,6BAAsB,AAAM,KAAD,GAAG;EACpD;uDAG8B,OACd;AAGD,IAAR,uCAA4B,KAAK,EAAE,UAAU;EACpD;iDAQ2B;AACT,IAAhB,qCAA+B,OAAO;EACxC;mDAO4B;;AAAY;;AAAiB,iBAAK,OAAO;;;EAAC;;;;AAGlE,cAAQ;6BACP,WAAM;IAEyB","file":"../../../../../../../../../packages/test_api/src/scaffolding/utils.dart.lib.js"}');
  // Exports:
  return {
    src__scaffolding__utils: utils
  };
}));

//# sourceMappingURL=utils.dart.lib.js.map
