// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
// Module: packages/ypo_connect/utils.dart
// Flags: newRuntimeTypes(true), soundNullSafety(true), enableAsserts(true)
define(['dart_sdk', 'packages/flutter/src/widgets/unique_widget.dart', 'packages/flutter_spinkit/src/rotating_circle.dart', 'packages/flutter/src/material/colors.dart', 'packages/flutter/src/painting/edge_insets.dart', 'packages/flutter_spinkit/src/three_in_out.dart'], (function load__packages__ypo_connect__utils_dart(dart_sdk, packages__flutter__src__widgets__unique_widget$46dart, packages__flutter_spinkit__src__rotating_circle$46dart, packages__flutter__src__material__colors$46dart, packages__flutter__src__painting__edge_insets$46dart, packages__flutter_spinkit__src__three_in_out$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const widget_inspector = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__widget_inspector;
  const basic = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__basic;
  const framework = packages__flutter__src__widgets__unique_widget$46dart.src__widgets__framework;
  const rotating_circle = packages__flutter_spinkit__src__rotating_circle$46dart.src__rotating_circle;
  const colors = packages__flutter__src__material__colors$46dart.src__material__colors;
  const edge_insets = packages__flutter__src__painting__edge_insets$46dart.src__painting__edge_insets;
  const three_in_out = packages__flutter_spinkit__src__three_in_out$46dart.src__three_in_out;
  var utils = Object.create(dart.library);
  dart._checkModuleNullSafetyMode(true);
  dart._checkModuleRuntimeTypes(true);
  var T = {
    BuildContextToWidget: () => (T.BuildContextToWidget = dart.constFn(dart_rti.findType("flutter__src__widgets__framework|Widget(flutter__src__widgets__framework|BuildContext)")))()
  };
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "MainLoading",
        [_Location_column]: 9,
        [_Location_line]: 8,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "SpinKitRotatingCircle",
        [_Location_column]: 14,
        [_Location_line]: 13,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Center",
        [_Location_column]: 12,
        [_Location_line]: 12,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C3() {
      return C[3] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "ResultsLoading",
        [_Location_column]: 9,
        [_Location_line]: 22,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C4() {
      return C[4] = dart.const(Object.setPrototypeOf({
        [EdgeInsets_bottom]: 80,
        [EdgeInsets_right]: 80,
        [EdgeInsets_top]: 80,
        [EdgeInsets_left]: 80
      }, edge_insets.EdgeInsets.prototype));
    },
    get C5() {
      return C[5] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "SpinKitThreeInOut",
        [_Location_column]: 16,
        [_Location_line]: 29,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C6() {
      return C[6] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Padding",
        [_Location_column]: 14,
        [_Location_line]: 27,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    },
    get C7() {
      return C[7] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "Center",
        [_Location_column]: 12,
        [_Location_line]: 26,
        [_Location_file]: "file:///Users/haggaibarel/StudioProjects/ypo_connect/lib/utils.dart"
      }, widget_inspector._Location.prototype));
    }
  }, false);
  var C = Array(8).fill(void 0);
  var I = ["package:ypo_connect/utils.dart"];
  var _Location_name = dart.privateName(widget_inspector, "_Location.name");
  var _Location_column = dart.privateName(widget_inspector, "_Location.column");
  var _Location_line = dart.privateName(widget_inspector, "_Location.line");
  var _Location_file = dart.privateName(widget_inspector, "_Location.file");
  utils.MainLoading = class MainLoading extends framework.StatelessWidget {
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      return new utils.MainLoading.new({key: key, $creationLocationd_0dea112b090073317d4: C[0] || CT.C0});
    }
    build(context) {
      return new basic.Center.new({child: new rotating_circle.SpinKitRotatingCircle.new({color: colors.Colors.blue, size: 80.0, $creationLocationd_0dea112b090073317d4: C[1] || CT.C1}), $creationLocationd_0dea112b090073317d4: C[2] || CT.C2});
    }
  };
  (utils.MainLoading.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    dart.global.Object.getPrototypeOf(utils.MainLoading).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = utils.MainLoading.prototype;
  dart.addTypeTests(utils.MainLoading);
  dart.addRtiResources(utils.MainLoading, ["ypo_connect__utils|MainLoading"]);
  dart.addTypeCaches(utils.MainLoading);
  dart.setMethodSignature(utils.MainLoading, () => dart.global.Object.setPrototypeOf({build: T.BuildContextToWidget()}, dart.getMethods(dart.global.Object.getPrototypeOf(utils.MainLoading))));
  dart.setLibraryUri(utils.MainLoading, I[0]);
  var EdgeInsets_bottom = dart.privateName(edge_insets, "EdgeInsets.bottom");
  var EdgeInsets_right = dart.privateName(edge_insets, "EdgeInsets.right");
  var EdgeInsets_top = dart.privateName(edge_insets, "EdgeInsets.top");
  var EdgeInsets_left = dart.privateName(edge_insets, "EdgeInsets.left");
  utils.ResultsLoading = class ResultsLoading extends framework.StatelessWidget {
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      return new utils.ResultsLoading.new({key: key, $creationLocationd_0dea112b090073317d4: C[3] || CT.C3});
    }
    build(context) {
      return new basic.Center.new({child: new basic.Padding.new({padding: C[4] || CT.C4, child: new three_in_out.SpinKitThreeInOut.new({color: colors.Colors.blue, size: 80.0, $creationLocationd_0dea112b090073317d4: C[5] || CT.C5}), $creationLocationd_0dea112b090073317d4: C[6] || CT.C6}), $creationLocationd_0dea112b090073317d4: C[7] || CT.C7});
    }
  };
  (utils.ResultsLoading.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    dart.global.Object.getPrototypeOf(utils.ResultsLoading).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = utils.ResultsLoading.prototype;
  dart.addTypeTests(utils.ResultsLoading);
  dart.addRtiResources(utils.ResultsLoading, ["ypo_connect__utils|ResultsLoading"]);
  dart.addTypeCaches(utils.ResultsLoading);
  dart.setMethodSignature(utils.ResultsLoading, () => dart.global.Object.setPrototypeOf({build: T.BuildContextToWidget()}, dart.getMethods(dart.global.Object.getPrototypeOf(utils.ResultsLoading))));
  dart.setLibraryUri(utils.ResultsLoading, I[0]);
  dart.moduleConstCaches.set("packages/ypo_connect/utils.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"flutter__src__widgets__framework|Widget":{"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__foundation__diagnostics|DiagnosticableTree":{"flutter__src__foundation__diagnostics|Diagnosticable":[]},"ypo_connect__utils|MainLoading":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__widgets__framework|StatelessWidget":{"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"ypo_connect__utils|ResultsLoading":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]}}'));
  dart.trackLibraries("packages/ypo_connect/utils.dart", {
    "package:ypo_connect/utils.dart": utils
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["utils.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAU4B;AACxB,YAAO,8BACE,sDACS,0BACR;IAGZ;;;QAVwB;;AAAQ,8EAAW,GAAG;;EAAC;;;;;;;;;;;;;;;UAiBrB;AACxB,YAAO,8BACE,sDAEE,+CACS,0BACR;IAId;;;QAb2B;;AAAQ,iFAAW,GAAG;;EAAC","file":"../../../../../packages/ypo_connect/utils.dart.lib.js"}');
  // Exports:
  return {
    utils: utils
  };
}));

//# sourceMappingURL=utils.dart.lib.js.map
